.codecov.yml, .gitignore, LICENSE, Pipfile, Pipfile.lock, config.py, response_operations_ui/__init__.py, response_operations_ui/logger_config.py, response_operations_ui/views/hello.py, run.py
Set up initial folder structure and app initialisation
Set up one endpoint at home
Set up pipfile(.lock)
=> Initial flask setup

Pipfile, Pipfile.lock, Procfile, README.md, manifest.yml
Added Procfile and manifest.yml for cloudfoundry deployment
There is a version of the application currently pushed to the dev environment [here](http://response-operations-ui-dev.apps.devtest.onsclofo.uk)
=> Prepare repo for cloudfoundry push

response_operations_ui/__init__.py, response_operations_ui/logger_config.py, response_operations_ui/views/info.py, tests/test_info.py
Also added tests for this endpoint
=> Add info endpoint

response_operations_ui/templates/surveys.html
It's not ideal to use css classes to access the dom in acceptance testing as they are often changed so I have added a couple of ids and names to hang off
=> Adding attributes for the purpose of acceptance testing

Dockerfile, response_operations_ui/templates/surveys.html
Creating a dockerfile to be able to automatically create docker images with docker automation build https://hub.docker.com/r/sdcplatform/response-operations-ui/builds/ and updating legalbasis to match rm-survey-service json https://github.com/ONSdigital/rm-survey-service/pull/22/files#diff-4ec151648ae4c97b4d1668a4def08459R31
=> Create Dockerfile and update legalBasis

response_operations_ui/templates/survey.html
UI was updated to include this small change
=> Update "Title" to "Survey title"

response_operations_ui/templates/collection-exercise.html
Use `exerciseRef` instead of `name` for the collection exercise period
=> Use correct attribute for period fields

LICENSE
=> Update license attribution

response_operations_ui/templates/collection-exercise.html
* Use correct variables
* Add extra information
=> Change page title

response_operations_ui/controllers/sample_controllers.py, response_operations_ui/static/js/read-csv.js, response_operations_ui/templates/collection-exercise.html, response_operations_ui/views/collection_exercise.py, tests/test_data/collection_exercise/collection_exercise_details.json, tests/test_data/collection_exercise/collection_exercise_details_no_sample.json, tests/views/test_collection_exercise.py
As a CEC when a sample is loaded in to a CE
I need to understand the content of a sample
So that I am reasonably assured that it is the right sample file for the collection exercise
=> US0010 view sample

response_operations_ui/templates/sign_in.html
Adding an id for the integration tests
=> add sign in button id

response_operations_ui/templates/partials/header.html
Add id to sign out button for integration tests.
=> Add ID to sign out button

response_operations_ui/templates/sign_in.html, response_operations_ui/views/logout.py, tests/views/test_sign_in.py
First attempt to make it look like the designs in confluence (Found here for those who have access: https://digitaleq.atlassian.net/wiki/spaces/RASB/pages/226230282/US048+Internal+User+Signs+into+SDC)
The styles aren't perfect as a number of stylesheets are only in the CDN, which I think we're still on the fence about using.
=> Apply additional styling to login page

response_operations_ui/logger_config.py
Pass stdout as stream for logging rather than using default stderr.
=> Change logging to stream stdout

response_operations_ui/templates/sign_in.html
This ID is needed for the integration tests for the sign out features to pass 
https://github.com/ONSdigital/ras-integration-tests/pull/31
=> add id to successful sign out message

response_operations_ui/controllers/reporting_units_controllers.py, response_operations_ui/forms.py, response_operations_ui/static/js/read-csv.js, response_operations_ui/static/scss/base.scss, response_operations_ui/static/scss/components/search.scss, response_operations_ui/templates/reporting-units.html, response_operations_ui/views/__init__.py, response_operations_ui/views/reporting_units.py, tests/views/test_reporting_units.py
As an:
internal User
I need:
to be able to 'find' a Reporting Unit (RU Ref for Business Surveys)
So that:
I can easily locate the RU to deal with any issues
Dependencies:
https://github.com/ONSdigital/ras-backstage/pull/48
https://github.com/ONSdigital/ras-party/pull/99
=> Us043 find an ru

response_operations_ui/templates/partials/header.html, response_operations_ui/templates/survey.html, response_operations_ui/views/surveys.py, tests/test_data/survey/survey.json, tests/test_data/survey/survey_states.json, tests/views/test_survey.py
[https://trello.com/c/kJO9QkLd](https://trello.com/c/kJO9QkLd)
Added status column and data to the survey details page.
Data needs to be loaded in to test this functionality.
Don't merge until other user stories related to this card have been tested against this PR.
These states might change as they are, but the mapping functionality works.
=> US011 - Display state of a collection exercise

response_operations_ui/templates/sign_in.html
This way of displaying errors means that 1) every error will be displayed if there are mulitple and
2) the errors that are generated have links
=> Improve the way login errors are generated

response_operations_ui/static/scss/base.scss, response_operations_ui/static/scss/headings.scss, response_operations_ui/templates/reporting-unit.html, response_operations_ui/views/reporting_units.py, tests/test_data/reporting_units/reporting_unit.json, tests/views/test_reporting_units.py
As an: internal user
I need: to be able to view the surveys & CEs associated to the RU Ref
So that: I can understand for any RU Ref, the surveys and CEs  they are selected for
Dependencies: https://github.com/ONSdigital/ras-backstage/pull/52
=> Us045 view surveys for an ru

response_operations_ui/templates/collection-exercise.html, response_operations_ui/templates/partials/header.html, response_operations_ui/templates/survey.html, response_operations_ui/views/collection_exercise.py
Dependent on US011. Covers the UI for US047, US042, US040, US028 and US041. Adds the collection exercise state to the collection exercise details page.
=> View collection exercise state on ce details page

response_operations_ui/static/scss/base.scss, response_operations_ui/templates/reporting-unit.html, response_operations_ui/views/reporting_units.py, tests/test_data/reporting_units/reporting_unit.json, tests/views/test_reporting_units.py
As an: internal user
I need: to be able to view respondent data for a Reporting Unit for a specific survey
So that: I understand the relationships with respondents for the Reporting Unit across surveys
Dependencies:
https://github.com/ONSdigital/ras-backstage/pull/53
=> add respondents for ru per survey

response_operations_ui/static/scss/components/info_panel.scss, response_operations_ui/templates/collection-exercise.html
=> Increase size and move inline state of ce to match design

response_operations_ui/templates/messages.html, response_operations_ui/templates/partials/header.html, response_operations_ui/views/messages.py
Amendments for the integration tests (https://github.com/ONSdigital/ras-integration-tests/pull/50)
=> Add message

response_operations_ui/controllers/collection_instrument_controllers.py, response_operations_ui/templates/collection-exercise.html, response_operations_ui/templates/layouts/base.html, response_operations_ui/views/collection_exercise.py, tests/test_data/collection_exercise/collection_exercise_details.json, tests/test_data/collection_exercise/collection_exercise_details_no_ci.json, tests/test_data/collection_exercise/collection_exercise_details_no_sample.json, tests/views/test_collection_exercise.py
Scenario: The user is able to select the eQ collection instruments to load into the collection exercise
Given the internal user navigates to the collection exercise details page for QBS 1803
When the user selects the collection instrument
Then the collection instrument is added into the collection exercise
=> Us029 select eq ci

response_operations_ui/templates/collection-exercise.html, response_operations_ui/views/collection_exercise.py, tests/views/test_collection_exercise.py
Also changes success messages to use the new info panel style
=> US028 Show info bar for in-processing Collection Exercise

response_operations_ui/common/mappers.py, tests/test_data/survey/survey_states.json, tests/views/test_survey.py
=> Match standard case for state to designs

.gitignore, Pipfile, Pipfile.lock, config.py, response_operations_ui/__init__.py, response_operations_ui/cloud/cloudfoundry.py, response_operations_ui/controllers/message_controllers.py, response_operations_ui/user.py, response_operations_ui/views/info.py, response_operations_ui/views/messages.py, response_operations_ui/views/sign_in.py, tests/views/test_message.py, tests/views/test_sign_in.py
Implementing server side sessions with REDIS. This is too allow us to store the UAA token in redis for later use.
=> Flask Server side sessions with REDIS

response_operations_ui/__init__.py, response_operations_ui/cloud/cloudfoundry.py
The redis look up failed as it was working outside the flask application context.
=> Fixing REDIS look up in Cloud foundry

response_operations_ui/__init__.py, response_operations_ui/cloud/cloudfoundry.py, response_operations_ui/templates/home.html
The link is now redundant so should be removed.
Also two minor style fixes because I couldn't run `make test` without fixing them.
=> Remove Home Page 'Create Message' Link

response_operations_ui/views/messages.py
In Secure message display first and last name in the inbox view rather than UUID
=> SM: Display first and last name instead of UUID in from

response_operations_ui/templates/reporting-unit.html, response_operations_ui/views/reporting_units.py
Display trading as name for the reporting unit and for each collection exercise
Works with [backstage PR](https://github.com/ONSdigital/ras-backstage/pull/82)
=> Use tradstyle fields for trading as name

response_operations_ui/static/css/components/nav.css, response_operations_ui/static/css/override.css, response_operations_ui/templates/create-message.html, response_operations_ui/templates/messages.html, response_operations_ui/templates/reporting-unit.html
This pull request aims to fix some of the css problems in response operations UI for creating a message.
-  Fixed the tabs at the top of the page so the border doesn't hang
- Changed create message button to look like a link
- Turned the create message page so it looks like designs
=> Fixing some CSS bugs

response_operations_ui/common/surveys.py, response_operations_ui/templates/create-message.html, response_operations_ui/templates/messages.html
Made a couple of simple UI changes.
- Required validation on create message field.
- Filter survey list order.
- System feedback (message sent) above headings.
=> UI iterations

response_operations_ui/templates/reporting-unit.html
related to https://github.com/ONSdigital/ras-party/pull/121 and https://github.com/ONSdigital/ras-backstage/pull/94
=> update to use trading_as rather than name for Trading As

response_operations_ui/templates/reporting-unit.html
Forgot to pass trading as into the template
=> Pass trading_as into change enrolment template

response_operations_ui/controllers/collection_instrument_controllers.py, response_operations_ui/static/css/components/icons.css, response_operations_ui/static/css/components/table.css, response_operations_ui/static/images/ic_remove_circle_outline_black_18px.svg, response_operations_ui/templates/collection-exercise.html, response_operations_ui/views/collection_exercise.py, tests/views/test_collection_exercise.py
As a: CEC
I need: to be able to remove a loaded SEFT CI
So that: the correct CI is associated to the RU
https://trello.com/c/LhzrsVoU/69-us059-remove-seft-loaded-ci-s
=> Us059 remove loaded ci

response_operations_ui/templates/collection-exercise.html, response_operations_ui/views/collection_exercise.py
Replaced if statements in html template for each success panel message with a general success panel information.
=> Refactor success panel

response_operations_ui/templates/partials/header.html
Adds skip to content banner for accessibility.
=> Add skip to content banner

response_operations_ui/common/surveys.py
=> Add MBS to survey filter list

.github/PULL_REQUEST_TEMPLATE.md
Adding a section to suggest when opening a PR to link out to any relevant information
Add link section for:
* Other related PRs
* Links to documentation
* Link to trello or github issues
Check link section is added after it is merged to master
=> Add links sections to github PR template

response_operations_ui/controllers/reporting_units_controllers.py, tests/views/test_reporting_units.py
Remove unused code and ensure all of the reporting unit controller uses the same raise_for_status pattern for error handling. 
Run the unit and acceptance tests for 🍰
=> Remove unused test URLs and use raise for status pattern

response_operations_ui/controllers/survey_controllers.py, tests/views/test_survey.py
Removing proxying network requests to backstage by calling the services directly.
Change to update a survey's details direct through the survey service rather than proxying through the backstage service.
=> [TBL] Update details direct with survey service

response_operations_ui/controllers/collection_exercise_controllers.py, response_operations_ui/views/collection_exercise.py, tests/views/test_collection_exercise.py
Removing proxying network requests to backstage by calling the services directly.
Change to execute a collection exercise direct through the collection exercise service rather than proxying through the backstage service.
=> [TBL] Set ready for live direct

config.py, response_operations_ui/controllers/message_controllers.py, tests/views/test_collection_exercise.py
Once ~#195~ ~#197~ ~#198~ have been merged we should be able to remove the config for Backstage from this repo.
- [Trello](https://trello.com/c/0lPdzRbt)
- [Remove from docker PR](https://github.com/ONSdigital/ras-rm-docker-dev/pull/64)
- [Remove from pipeline PR](https://github.com/ONSdigital/ras-deploy/pull/31)
=> [TBL] Remove backstage url from config

response_operations_ui/__init__.py
Recent change that went in causing ROps to break due to it being unable to set up Redis correctly.
Fix for commit: https://github.com/ONSdigital/response-operations-ui/commit/9c06b1703b8518f11b7800034b6b03358d08ba74
Make sure all tests pass and test with Docker
Also, if you have access push it up to the CF dev space to check if the app starts up correctly
=> Fix for Redis Issue

response_operations_ui/views/info.py
bump version to 0.7.2
change version in views/info.py
=> bump version to v0.7.2

Pipfile, Pipfile.lock, config.py, response_operations_ui/__init__.py
This reverts commit f3adfabf7436d449ea8e9f5d5713f267206f7805.
=> Revert "ZipKin Tracing (#219)"

response_operations_ui/templates/social-view-case-details.html, response_operations_ui/templates/social.html, response_operations_ui/views/social/social_case_search.py, response_operations_ui/views/social/social_view_case_details.py, tests/test_data/sample/sample_attributes.json, tests/test_data/sample/sample_units.json, tests/views/test_social.py, tests/views/test_social_case.py
Due to the format of the social sample file changing we need to update the data being displayed back to the user from searching for a social postcode and viewing the data
Updated templates and unit tests associated with the changes and added new updated social sample test data
Run unit tests and ensure they pass, spin up manually and check info is all correct too
=> Social sample file pilot changes

response_operations_ui/views/info.py
bump version to 0.7.3
version in info endpoint
=> bump version to 0.7.3

response_operations_ui/common/dates.py, response_operations_ui/common/token_decoder.py, response_operations_ui/controllers/message_controllers.py, response_operations_ui/controllers/sample_controllers.py, response_operations_ui/forms.py, response_operations_ui/logger_config.py, response_operations_ui/static/images/logo-white.svg, response_operations_ui/views/collection_exercise.py, response_operations_ui/views/errors.py, response_operations_ui/views/info.py, response_operations_ui/views/messages.py, response_operations_ui/views/reporting_units.py, response_operations_ui/views/sign_in.py, response_operations_ui/views/surveys.py, response_operations_ui/views/update_event_date.py, tests/test_dates.py, tests/test_user.py, tests/views/test_collection_exercise.py, tests/views/test_create_app.py, tests/views/test_message.py, tests/views/test_social_case.py, tests/views/test_survey.py
=> Fix import ordering

response_operations_ui/logger_config.py, tests/test_logger_config.py
Align trace log information with Java services
=> Align trace naming in logs with other services.

response_operations_ui/templates/reporting-unit.html
=> Added ids for AT's

response_operations_ui/templates/partials/breadcrumbs.html
breadcrumbs id is needed for Acceptance tests
=> Added breadcrumbs id back in as required for acceptance tests

response_operations_ui/views/info.py
For next release, we need to bump the release tag
- Release number to v0.11.0
=> Updated version

response_operations_ui/views/info.py
=> Upd version

response_operations_ui/templates/conversation-view/cv-reply-form.html
Cancel button too close the close buttons
Added margin to the form to form so as to push button down . Not added to button as button repeats top and bottom
Run response ops and create message, see increased gap above cancel button
=> Added class to form to move back button down

response_operations_ui/views/info.py
=> Update version to 0.16.0

response_operations_ui/static/js/validate-ci.js
Bug fix, for a bug spotted in linked card.
Swapped out the offending functions.
Confirm error messages display properly on form validation for collection instrument creation, confirm acceptance tests are fixed.
=> Reversed actions of class manipulation

API.md
I have been looking through response-operations-ui and documenting the API endpoints.
Added API.md file to document endpoints.
[Trello card](https://trello.com/c/yIAqMY2Q)
=> Documenting endpoints

response_operations_ui/views/info.py
=> updating version

response_operations_ui/views/info.py
=> increase version

docs/frontend/Bundling with Webpack and Babel.md
Added documentation for webpack and babel.
https://trello.com/c/h8XKZEuF
=> Fe docs bundling

response_operations_ui/views/info.py
=> Update version number

response_operations_ui/views/info.py
=> update to version 1.0.0

response_operations_ui/controllers/uaa_controller.py, response_operations_ui/templates/forgot-password-check-email.html, response_operations_ui/templates/reset-password.html, response_operations_ui/templates/sign_in.html, response_operations_ui/views/passwords.py
There were a couple of issues in the reset password functionality - this fixes them
=> Fixing some redirect issues

response_operations_ui/views/info.py
=> upgrading version to 1.1.0

response_operations_ui/views/info.py
=> updating version to 1.1.1

response_operations_ui/views/info.py
Rolling back the version to 1.1.0 as otherwise it would be a broken release.
=> correct version for a working release

response_operations_ui/views/passwords.py
The wrong email was getting sent
=> Fix email confirmation

response_operations_ui/controllers/uaa_controller.py, response_operations_ui/views/passwords.py
The refactoring done to fix bugs introduced a regression - this fixes it
=> Issues around refactoring

response_operations_ui/controllers/party_controller.py
We didn't log out the ru_ref enough in the logging
Where ru_ref available, log it to make debugging easier
=> log out ru_ref

response_operations_ui/views/info.py
=> upgrade version

response_operations_ui/forms.py, response_operations_ui/templates/conversation-view/conversation-view.html, response_operations_ui/templates/conversation-view/cv-reply-form.html, response_operations_ui/templates/reporting-unit.html, response_operations_ui/views/messages.py, tests/test_data/message/thread.json, tests/test_data/message/thread_missing_respondent.json, tests/test_data/message/thread_missing_subject.json, tests/test_data/message/thread_unread.json, tests/test_data/message/threads.json, tests/test_data/message/threads_multipage.json, tests/test_data/message/threads_no_unread.json, tests/test_data/message/threads_unread.json, tests/views/test_message.py
When changing ru_id to business_id in secure message, there was more to do then change the payload received. We had to change what we sent to secure message
- Fix message send code
- Update test data
=> First pass at fixing secure messaging

response_operations_ui/views/info.py
release 1.7.0
using design system for secure messages
=> version 1.7.0 release

config.py
3 days wasn't long enough for the business.
=> Up the expiry to 6 weeks

_infra/helm/values.yaml
=> remove3 cpu:wq

_infra/helm/templates/ManagedCertificate.yaml, _infra/helm/templates/NetworkPolicy.yaml, _infra/helm/templates/deployment.yaml, _infra/helm/templates/ingress.yaml, _infra/helm/templates/service.yaml, _infra/helm/values.yaml
Added certificate and default network policy.
Instead of nodeport, it will default to ClusterIp service type and lbs are not required for acceptance testing.
=> add certs network policy and templated ingress

_infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml
=> separate database in config

_infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml
=> add add replicaCount tempalte

_infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/templates/ingress.yaml, _infra/helm/response-operations-ui/values.yaml
=> Standardise

_infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml
=> remove db config

_infra/docker/Dockerfile
=> Fix dockerfile

_infra/docker/Dockerfile, _infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/templates/service.yaml, _infra/helm/response-operations-ui/values.yaml
=> Fixes for kubernetes

_infra/helm/response-operations-ui/templates/ingress.yaml
=> Fix ingress template

_infra/helm/response-operations-ui/values.yaml
=> Rename managed certificate

_infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml
=> Add missing config

_infra/helm/response-operations-ui/templates/backendconfig.yaml, _infra/helm/response-operations-ui/templates/service.yaml
=> add cloud armour config

_infra/helm/response-operations-ui/values.yaml
=> Quote value

_infra/helm/response-operations-ui/templates/deployment.yaml
=> enclosing quotes

_infra/helm/response-operations-ui/templates/service.yaml
=> remvoe esape chars

_infra/helm/response-operations-ui/templates/deployment.yaml
=> Fix environment variable name

response_operations_ui/views/info.py
Change version number for release
version number 1.8.0 -> 1.9.0
https://trello.com/c/botlRPsE
=> version to 1.9.0

_infra/helm/response-operations-ui/templates/deployment.yaml
=> Add notify url

_infra/helm/response-operations-ui/templates/deployment.yaml
=> Fix link url

_infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml
=> Add template uuids for notifygateway

_infra/helm/response-operations-ui/templates/backendconfig.yaml
allows for session affinity based on client ip
added a tag within the backendconfig for session affinity
when it is merged and deployed it will show up in advanced config for backend services
=> added session affinity for Client IP to backendconfig.yaml files

_infra/spinnaker/deployment-full.json
=> add missing vars

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml
Adds kube_dns addresses for all connecting services to allow us to have circular references
=> Create DNS entries for each service

response_operations_ui/templates/layouts/spoke.html
The gtm script was missing from the spoke base template.
=> Added gtm script to spoke base template

_infra/helm/response-operations-ui/templates/ManagedCertificate.yaml, _infra/helm/response-operations-ui/templates/ingress.yaml, _infra/helm/response-operations-ui/values.yaml
=> add aws certs

_infra/helm/response-operations-ui/templates/backendconfig.yaml, _infra/helm/response-operations-ui/values.yaml
=> add timeout to backendConfig

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml
=> Fix account creation email links

_infra/helm/response-operations-ui/templates/deployment.yaml
=> Add missing trailing slash

response_operations_ui/templates/confirm-enrolment-change.html, response_operations_ui/templates/response-status.html
=> Adding missing CSRF token

response_operations_ui/templates/conversation-view/cv-reopen-form.html, response_operations_ui/templates/reporting-unit.html
=> Add missing csrf token

response_operations_ui/templates/layouts/base.html, response_operations_ui/templates/reporting-unit.html
This change is untested, please do so before approving
=> Add missing nonce tags to RU lookup page

response_operations_ui/templates/collection_exercise/ce-header-section.html, response_operations_ui/templates/collection_exercise/ce-instrument-section.html, response_operations_ui/templates/collection_exercise/ce-sample-section.html, response_operations_ui/templates/components/button/_macro.njk, response_operations_ui/templates/components/input/_macro.njk, response_operations_ui/templates/components/upload/_macro.njk
=> Attempt to make components play nice with CSP

_infra/helm/response-operations-ui/Chart.yaml
=> Increment chart version

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/messages.py
Fixes a security issue where HTML tags can be injected into the message subject
=> Escaping HTML in message subject

response_operations_ui/templates/collection_exercise/ce-instrument-section.html, response_operations_ui/templates/reporting-unit.html, response_operations_ui/templates/response-status.html
=> Add nonce to links with onclicks

response_operations_ui/templates/collection_exercise/ce-instrument-section.html, response_operations_ui/templates/reporting-unit.html, response_operations_ui/templates/response-status.html
Reverts ONSdigital/response-operations-ui#462
=> Revert "Add nonce to links with onclicks"

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-instrument-section.html
=> Rework how we add onclick

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-instrument-section.html
=> Can't access Jinja loop index in non-Jinja contexts

_infra/docker/Dockerfile, _infra/helm/response-operations-ui/Chart.yaml
=> Increasing timeout for gunicorn threads

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/layout/_template.njk, response_operations_ui/templates/layouts/spoke.html, response_operations_ui/templates/reporting-unit.html
Fixes ops call indicating that, with reporting units that have >1 respondent, only the first respondent can have their details edited.
=> Fix spoke scripting

_infra/helm/response-operations-ui/Chart.yaml, scripts/README.md, scripts/generate_csv_for_emails.py
=> Small text and doco fix

scripts/generate_csv_for_emails.py
Remove TRADING_STYLE as gov notify doesn't like empty variables.  Also added very light validation for email addresses.
=> Another email fix

_infra/helm/response-operations-ui/Chart.yaml
=> incremenet patch

response_operations_ui/templates/banner-admin.html
Add a max length of 200 but this is not required
=> Remove max length

.github/workflows/main.yml, _infra/helm/response-operations-ui/Chart.yaml
=> replace concourse

config.py
=> Remove pointless None default

Dockerfile, Pipfile, Pipfile.lock, _infra/docker/Dockerfile, _infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/messages.py, tests/controllers/test_admin_controller.py
=> Upgrade to python 3.8

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-nudge-email-section.html, response_operations_ui/views/collection_exercise.py, tests/views/test_collection_exercise.py
=> Sorted View for Nudge Email on month time and year

.github/workflows/comment.yml, .github/workflows/main.yml, _infra/helm/response-operations-ui/Chart.yaml
=> Make dev docker tag changes

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/collection_exercise.py
=> Date bug fix

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/collection_exercise.py
=> Sort nudge email bug fix

_infra/helm/response-operations-ui/Chart.yaml, package-lock.json, package.json
Fixing moderate security vulnerability in the npm and npx packages used for test of this app.
- updated `webpack-cli` and dependencies
- updated `stylelint` and dependencies
- removed deprecated `uglifyjs-webpack-plugin`, replaced by `terser-webpack-plugin` (which is already installed). This also removed the dependency `serialize-javascript`, which was the source of the moderate vulnerability.
`make test`
https://trello.com/c/gasqbNsu
=> Node package updates

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/common/filters.py, response_operations_ui/views/home.py, tests/views/test_home.py
Kept getting an error 500 page when using overview page in preprod.  Sample data comes as an int.  Needed to convert it to a string before it got to the template.
Also added more logging as it was a bit too light.
=> Add logging and fix sample data bug

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/common/dates.py, response_operations_ui/common/filters.py, response_operations_ui/common/mappers.py, response_operations_ui/common/token_decoder.py, response_operations_ui/templates/overview/overview-survey.html, response_operations_ui/views/home.py, tests/common/test_dates.py, tests/common/test_filters.py, tests/common/test_mappers.py, tests/views/test_home.py
The first version of the overview screen went in incomplete to make the PRs smaller/easier to understand and get it in sooner knowing we could iterate on it.
This PR contains the missing features from the prototype (https://rops-prototypes.netlify.app/prototypes/overview/version-one/index.html).
=> Add missing features for overview

_infra/helm/response-operations-ui/Chart.yaml, config.py, response_operations_ui/common/dates.py, tests/common/test_dates.py
Date time on the dash board is now localised and adjusted for daylight savings.
Add a new flag to the format datetime method to localise the date.
1. Browse to the dash board and check dates are correct
https://trello.com/c/ha5XugCD/2182-ritm0382675-vacancies-go-live-time-is-different-on-the-dashboard-than-on-the-surveys-page-screenshot-attatched
=> Date time on dashboard

_infra/helm/response-operations-ui/Chart.yaml, scripts/generate_csv_for_emails.py
=> Update script to include ru_ref and survey_id

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/surveys.html, tests/views/test_survey.py
Add functionality for users to create surveys.
Added a line of HTML linking to a function
=> able to create new survey

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-instrument-section.html
There wasn't a count of collection instruments that had been uploaded on the collection exercise screen.  This PR adds it so it's easier to see how many have been used for this collection exercise.
=> Add count of collection instruments

_infra/helm/response-operations-ui/Chart.yaml, _infra/spinnaker/deployment-full.json
=> syncronize default helm chart

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-header-section.html
=> Go_live confirmation button fix

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/components/button/_macro.njk, response_operations_ui/templates/components/input/_macro.njk, response_operations_ui/templates/components/upload/_macro.njk
One up the updates to the design system removed listeners.  We'll readd what was missing to get it work for now and a more permanent fix will be included later on.
=> First pass at fixing tests

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/create-ce-event.html, response_operations_ui/templates/update-event-date.html
=> reverted date and time fields

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-instrument-section.html, tests/test_data/collection_exercise/seft_collection_exercise_details.json, tests/views/test_collection_exercise.py
=> Bug fix for SEFT collection instrument

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/collection_exercise.py
=> Fix temporary list of SEFT surveys

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/collection_exercise.py
=> Fix missing comma

.github/workflows/main.yml, _infra/helm/response-operations-ui/Chart.yaml, _infra/spinnaker/prodDeploy.json
Update needed to hash in production pipeline, to use template with release parameters.
Also updated GH Actions to ignore Spinnaker changes in build trigger.
- https://collaborate2.ons.gov.uk/jira/browse/RAS-141
=> update SHA in prod template, exclude spinnaker from GH triggers

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/create-ce-event.html
Fixed the following issue in `create-ce-event` template:
- Guidance text was being displayed as part of the error but should be persistent. Now fixed.
=> Fixed issues with create ce event

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/create-ce-event.html, response_operations_ui/templates/messages.html
Fixes issue where unread messages were not displayed in bold.
=> Fix bold text in unread messages 

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/surveys.py
=> Add epe to EQ list

.github/workflows/comment.yml, _infra/helm/response-operations-ui/Chart.yaml
=> change from sandbox to dev

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/common/respondent_utils.py, response_operations_ui/controllers/party_controller.py, response_operations_ui/templates/respondent-search/rs-table.html, response_operations_ui/views/case.py
The responded was being referenced from reporting unit after deletion which causes 500 error
logic has been added to avoid 500 errors
Smoke test and business approval required
[Trello](https://trello.com/c/NzvpAaU3/185-bug-respondent-delete-bugs)
=> Bug fix for respondent being referenced after deletion

_infra/helm/response-operations-ui/Chart.yaml
=> bumping chart version for the build failure

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/remove-alert.html, response_operations_ui/views/admin.py
CSRF added to remove-alert.html to fix 500 error in preprod. Unused to and imports also removed
Code changed
=> CSRF added to remove-alert.html

.github/workflows/comment.yml, _infra/helm/response-operations-ui/Chart.yaml
=> injection fix

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/collection_exercise_controllers.py, response_operations_ui/controllers/notify_controller.py, response_operations_ui/views/reporting_units.py, tests/views/test_reporting_units.py
During a spike around the reporting unit page, I noticed that some of it was hard to follow as it wasn't clear exactly what types certain variables were or what the function was actually doing at a glance.  
- Added docstrings to a number of functions
- Made a small performance improvement to the reporting unit page by removing unnecessary work
=> Document ru page

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/templates/external-secrets.yaml, _infra/helm/response-operations-ui/values.yaml
=> add external secrets

.github/workflows/comment.yml, _infra/helm/response-operations-ui/Chart.yaml
Use new github action created specifically for ras-rm pr comments.
https://github.com/ONSdigital/ras-rm-spinnaker-action
=> new comment action

.github/workflows/main.yml, Dockerfile, Pipfile, Pipfile.lock, _infra/docker/Dockerfile, _infra/helm/response-operations-ui/Chart.yaml
Upgrade python from 3.8 to 3.9 to keep it current
=> Upgrade python to 3.9

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/messages.py, tests/views/test_message.py
=> Fix redirection in message creation

_infra/helm/response-operations-ui/Chart.yaml
=> Bump chart version

response_operations_ui/templates/response-status.html
fixing un secure error issue while submitting respondent completed on phone or no longer required.
=> fixing insecure error issue

response_operations_ui/controllers/survey_controllers.py
=> Tidy docstrings

response_operations_ui/templates/admin/banner-manage.html, response_operations_ui/templates/admin/banner-view-message-template.html, response_operations_ui/views/admin.py, tests/views/test_banner_view_message_template.py
[Trello](https://trello.com/c/y1rYRJQb/209-s29-alert-banner-management-javascript-off)
=> Alert banner management on javascript off 

README.md, _infra/helm/response-operations-ui/Chart.yaml
=> Remove unused badges

Pipfile.lock, _infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-nudge-email-section.html
the text for creating nudge email bug.
create nudge email
https://trello.com/c/8WgmVhVN/600-content-issue-make-nudge-email-text-sentence-case
=> Make nudge email text content fix

_infra/helm/response-operations-ui/Chart.yaml, scripts/generate_csv_for_emails.py
Added two new surveys to the generate script
=> added AIFDI and AOFDI surveys to generate script

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/delete-respondent.html, response_operations_ui/templates/respondent-search/respondent-search.html, response_operations_ui/templates/respondent.html, response_operations_ui/views/respondents.py, tests/views/test_respondents.py
Respondent delete UI modified to make it more clear
https://trello.com/c/MDOLH1pz/626-bug-enhancement-for-the-response-operation-ui-respondent-account-deletion-journey
=> Respondent delete UI modified to make it more clear

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/admin_controller.py
The versions being deployed were off for reasons... This PR manually bumps it 2 higher to eliminate any issues and adds typehints as a bonus
=> Update appversion and typehints

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/admin/banner-manage.html, response_operations_ui/templates/admin/template-create.html, response_operations_ui/templates/admin/template-edit.html, response_operations_ui/templates/conversation-view/cv-reply-form.html
Banner management page is failing after the design system update
Check banner management functionality.
https://trello.com/c/ZKa2wYN4/670-bug-banner-page-erroring-out
=> modified max limit to charCheckLimit for failing template render

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/reporting-unit-survey.html, response_operations_ui/templates/reporting-unit.html, response_operations_ui/views/reporting_units.py
=> Fix broken functionality

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/messages.py, tests/views/test_message.py
The filter in the technical inbox was breaking when used.  This PR fixes it and also fixes the clear filter button that was also broken
=> Fix bug in filter

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/reporting_units.py
We were showing the first case of *any* collection exercise, not the first case of the collection exercise for the survey
=> Fix display bug with IACs

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/message-select-survey.html, response_operations_ui/templates/secure-message/misc-inbox.html, response_operations_ui/views/messages.py, tests/views/test_message.py
https://trello.com/c/876SlD64/634-s36-user-account-creation-rops-changes-to-accommodate-rft-specific-messages
=> rOps changes to accommodate RFT specific messages

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/layouts/configs/navigation.html
https://trello.com/c/JJGvU0f4/736-bug-messages-tab-landing-on-500-error-message
=> Message tab fix

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/party_controller.py, response_operations_ui/templates/respondent.html
https://trello.com/c/lMi93wum/772-transfer-survey-changes-to-rops
=> Respondent detail change to afirm with transfer surveys

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/secure-message/change-thread-category-errors.html, response_operations_ui/views/messages.py
Fixes the lack of display for the flashed error message when something goes wrong in changing the category (before it would just refresh the page with no visual indicator that anything had happened).
=> Fix category bugs

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/party_controller.py
https://trello.com/c/lMi93wum/772-transfer-survey-changes-to-rops
=> silly mistake fix

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/respondent.html
=> Another silly mistake on template

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml, config.py, response_operations_ui/templates/conversation-view/cv-message-info.html, response_operations_ui/views/messages.py
=> Feature flag change category functionality

.github/workflows/main.yml, _infra/helm/response-operations-ui/Chart.yaml
=> Update chart versions automatically

Dockerfile, _infra/docker/Dockerfile, _infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml, config.py, response_operations_ui/templates/conversation-view/cv-message-info.html, response_operations_ui/views/messages.py
Now that the change category/survey feature is in production we can remove the feature flag toggle for it as we'd never want to switch it off.
=> Remove changeCategoryEnabled flag

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/respondents.py
https://trello.com/c/Vuy1RGTM/918-s43a-bug-delete-user-breadcrumb-in-rops
=> Bug fix to remove incorrect breadcrumb

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/values.yaml
reduce gcp costs
acceptance testing in namespacwe
https://trello.com/c/uTauehvU/1046-modify-resource-request-collection-instrument
=> revised limit values

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml
https://trello.com/c/NZ30BXlz/1096-bug-fix-response-ops-chart
=> Fix typo in config

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/ManagedCertificate.yaml
=> Managed Cert v1

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/common/filters.py, response_operations_ui/templates/overview/overview-sample.html, response_operations_ui/views/home.py, tests/common/test_filters.py
https://trello.com/c/cWQOE5je/1061-bug-responses-dashboard-404-error
=> Bug 404 response dashboard

Makefile, _infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/reporting_units_controllers.py, response_operations_ui/views/reporting_units.py
https://trello.com/c/XjLiwqc8/1004-spike-response-operations-performance-reporting-unit-page-1-2-days
=> Improving reporting unit search

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/reporting_units.py
Bug on pagination respondent search
=> pagination error introduced in error

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/case_controller.py, response_operations_ui/templates/response-status.html
https://trello.com/c/7VEdT3IE/910-allow-change-to-not-started-for-a-submission-in-response-operations-ui
=> Adding not started to case change

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/reporting_units_controllers.py, response_operations_ui/controllers/respondent_controllers.py, response_operations_ui/templates/reporting-unit-respondents.html, response_operations_ui/views/reporting_units.py, response_operations_ui/views/respondents.py, tests/views/test_reporting_units.py, tests/views/test_respondents.py
https://trello.com/c/yk676X1g/1225-change-rops-resend-email-to-use-the-new-template
=> updating verification email templates

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/reporting-unit-survey.html, response_operations_ui/templates/response-status.html, response_operations_ui/views/case.py
https://trello.com/c/7VEdT3IE/910-allow-change-to-not-started-for-a-submission-in-response-operations-ui
=> no longer required to not started

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/respondent_controllers.py, response_operations_ui/templates/re-send-verification-email.html, response_operations_ui/templates/respondent.html, response_operations_ui/views/respondents.py, tests/views/test_respondents.py
https://trello.com/c/yk676X1g/1225-change-rops-resend-email-to-use-the-new-template
=> Bug Fix for resend email

_infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml, config.py, response_operations_ui/__init__.py, response_operations_ui/controllers/notify_controller.py, response_operations_ui/controllers/uaa_controller.py, response_operations_ui/forms.py, response_operations_ui/templates/account/change-password.html, response_operations_ui/templates/account/my-account.html, response_operations_ui/templates/sign_in.html, response_operations_ui/views/accounts.py, response_operations_ui/views/logout.py, tests/views/test_accounts.py
https://trello.com/c/KZ7ZpmW3/1262-rops-ui-self-service-change-password
=> change password changes

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/account/confirm-email-change.html, response_operations_ui/views/accounts.py, tests/views/test_accounts.py
Making sure that only the original user who requested the email change can use the change email link
=> Check user id change email

Pipfile.lock, _infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml, config.py, response_operations_ui/templates/layouts/configs/navigation.html, response_operations_ui/templates/sign_in.html, response_operations_ui/views/sign_in.py, tests/views/test_sign_in.py
https://trello.com/c/fNnw4omM/1383-role-based-access-login-page-alterations
=> Sign in page update

_infra/helm/response-operations-ui/Chart.yaml, config.py
=> fix config issue

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/admin/manage-user-accounts.html, response_operations_ui/views/admin/manage_user_accounts.py
https://trello.com/c/xEOtfFqB/1385-role-based-access-manage-user-accounts
=> update design system

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/__init__.py, response_operations_ui/common/mappers.py, response_operations_ui/templates/admin/manage-user-accounts.html, response_operations_ui/templates/survey.html, response_operations_ui/views/surveys.py, tests/common/test_filters.py, tests/test_data/collection_exercise/ce_events_by_id.json, tests/test_data/collection_exercise/closest_future_collection_exercise.json, tests/test_data/collection_exercise/closest_past_collection_exercise.json, tests/test_data/collection_exercise/collection_exercise_details.json, tests/test_data/collection_exercise/collection_exercise_details_eq_both_ref_date.json, tests/test_data/collection_exercise/collection_exercise_details_eq_non_ref_date.json, tests/test_data/collection_exercise/collection_exercise_details_eq_ref_end_date.json, tests/test_data/collection_exercise/collection_exercise_details_eq_ref_start_date.json, tests/test_data/collection_exercise/collection_exercise_details_failedvalidation.json, tests/test_data/collection_exercise/collection_exercise_details_no_ci.json, tests/test_data/collection_exercise/collection_exercise_details_no_sample.json, tests/test_data/collection_exercise/events.json, tests/test_data/collection_exercise/events_2030.json, tests/test_data/collection_exercise/mixed_past_and_future_collection_exercises.json, tests/test_data/collection_exercise/multiple_same_start_collection_exercises.json, tests/test_data/collection_exercise/nudge_events_one.json, tests/test_data/collection_exercise/nudge_events_two.json, tests/test_data/collection_exercise/only_future_collection_exercises.json, tests/test_data/collection_exercise/only_past_collection_exercises.json, tests/views/test_collection_exercise.py, tests/views/test_survey.py
https://trello.com/c/rjpW5h7r/1415-rops-event-status-survey-screen
=> Adding event status on survey screen

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-sample-section.html
Cucumber test case failure fix for sample upload
=> Cucumber test fix

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/respondent.html, response_operations_ui/views/respondents.py, tests/views/test_respondents.py
https://trello.com/c/TUogZ7sY/1402-role-based-access-setup-user-groupings-respondent-tab
=> role based access respondent changes

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/__init__.py, response_operations_ui/controllers/uaa_controller.py
As suspected, having RBA permissions be responsive wasn't performant. This caches them in the session with a 5 minute expiry
https://trello.com/c/BJ7psPPX/1562-role-based-access-implementation-changes
=> Change RBA to be cached

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/survey.html, response_operations_ui/templates/update-event-date.html, response_operations_ui/views/surveys.py
A UI update to the collection exercise overview page
https://trello.com/c/tjhZWp42/1600-rops-improvements-collection-exercise-overview-page-cleanup
=> Collection exercise page cleanup

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-header-section.html
=> Show link when exercise ended

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/admin/manage_user_accounts.py
=> Handle csrf_token being in form

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/values.yaml
Sets the role based access flag to true
=> Switch on Role Based Access

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/forms.py, response_operations_ui/templates/account/change-password.html, response_operations_ui/templates/create-new-account.html, response_operations_ui/templates/reset-password.html, response_operations_ui/views/accounts.py, response_operations_ui/views/passwords.py, tests/test_forms.py
=> Refactor and combine password forms.  Also set min password length to 12.

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/uaa_controller.py, response_operations_ui/views/accounts.py, tests/views/test_accounts.py
=> Fix error logging on change password

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/sign_in.html, tests/views/test_sign_in.py
Update Username on signing page to email address
Make sure the change has been made when logging in
=> Change username to email on sign-in

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/conversation-view/cv-message-info.html
This pr adds a link to the ru ref already present in a secure message thread and allows users to go directly to see that ru from the message.
Make sure the link takes a user to the correct ru
=> Adding link to ru ref

Pipfile.lock, _infra/helm/response-operations-ui/Chart.yaml
=> Updating Pipfile.lock

Makefile, Pipfile, Pipfile.lock, pyproject.toml, response_operations_ui/__init__.py, response_operations_ui/templates/account/change-account-name.html, response_operations_ui/templates/account/change-email.html, response_operations_ui/templates/account/change-password.html, response_operations_ui/templates/account/change-username.html, response_operations_ui/templates/account/my-account.html, response_operations_ui/templates/admin/banner-manage.html, response_operations_ui/templates/admin/manage-user-accounts.html, response_operations_ui/templates/admin/user-delete.html, response_operations_ui/templates/ce-seft-instrument.html, response_operations_ui/templates/collection_exercise/ce-collection-instrument-section.html, response_operations_ui/templates/collection_exercise/ce-handle-errors.html, response_operations_ui/templates/collection_exercise/ce-info-section.html, response_operations_ui/templates/collection_exercise/ce-sample-ci-section.html, response_operations_ui/templates/collection_exercise/ce-sample-section.html, response_operations_ui/templates/collection_exercise/ce-upload-sample-file.html, response_operations_ui/templates/create-collection-exercise.html, response_operations_ui/templates/edit-contact-details.html, response_operations_ui/templates/edit-survey-details.html, response_operations_ui/templates/layouts/base.html, response_operations_ui/templates/reporting-unit-respondents.html, response_operations_ui/templates/reporting-unit.html, response_operations_ui/templates/respondent.html, response_operations_ui/templates/surveys.html, response_operations_ui/templates/update-event-date.html, tests/views/test_collection_exercise.py
DJlint installed and configured to improve html by removing linting errors in code.
Added ignore codes for inline styling and for empty class tags.
Updated tests after removing html entity codes.
- run make lint and make test
- check webpages for errors after html updates.
https://trello.com/c/MD1piAK2/2156-add-html-linter-djlint-to-response-operations-ui
=> Add linter

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/uaa_controller.py, response_operations_ui/views/admin/manage_user_accounts.py, tests/controllers/test_uaa_controller.py
This PR adds extra logging for IA to record who requests a RBA change
Do the steps on the story and make sure the correct log info are written out
N.B Happy to change the name of things, couldn't really think of anything at the time
=> Increase logging around RBA

.github/workflows/main.yml, Makefile, _infra/helm/response-operations-ui/Chart.yaml
Removal of deprecated github action
https://trello.com/c/JyPxSmDA/2298-replace-soon-to-be-deprecated-set-output-in-github-actions
=> Fix setoutput

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-action-dates-section.html, response_operations_ui/templates/collection_exercise/ce-ci-section.html, response_operations_ui/templates/collection_exercise/ce-info-section.html, response_operations_ui/templates/collection_exercise/ce-sample-section.html, response_operations_ui/templates/collection_exercise/collection-exercise.html, response_operations_ui/views/collection_exercise.py, tests/views/test_collection_exercise.py
=> Revert changes back to fix acceptance tests

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/create-collection-exercise.html
Further fixes for Dina's design review comments
https://trello.com/c/3b7gH0cK/2264-rops-design-improvement-collection-exercise-overview-page
=> Fixes for design review comments

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-ci-section.html, tests/views/test_collection_exercise.py
=> Change ID of link

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-ci-section.html, response_operations_ui/templates/collection_exercise/ce-sample-section.html, tests/views/test_collection_exercise.py
Changes to code based on Dina's requirements.
=> Change to design based on Dinas requirements

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/reporting-unit-survey.html, response_operations_ui/templates/reporting-unit.html
This PR updates the status indicators for collection exercises on the Reporting unit tabs. The change bring the indicators in line with the design system. 
Check the indicators are displayed as per the design suggestions on all RU tabs
https://trello.com/c/w2mz0sML/2458-rops-usability-enhancement-ru-tab-ce-completion-status-indicator-changes
=> Update ce status indicator

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/forms.py, response_operations_ui/templates/admin/manage-account.html, response_operations_ui/templates/admin/user-create.html, response_operations_ui/views/admin/manage_user_accounts.py
=> Add survey delete permission to create and edit

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/ce-seft-instrument.html, response_operations_ui/templates/collection_exercise/ce-collection-instrument-section.html, tests/views/test_collection_exercise.py
Minor fixes to response ops after design review
https://jira.ons.gov.uk/browse/RAS-267
=> fix subtitle for upload SEFT files

Pipfile, Pipfile.lock, response_operations_ui/__init__.py, response_operations_ui/templates/ce-seft-instrument.html
Dina commented that the lack of space between seft upload and listed SEFTs didnt look good, had added some padding to give some space
=> add padding to SEFT CI upload

Pipfile.lock, _infra/helm/response-operations-ui/Chart.yaml, package-lock.json, package.json
Update the missing dependabot ones I missed
Check everything still works
=> RAS-837 Rops Security Alerts

Pipfile.lock, _infra/helm/response-operations-ui/Chart.yaml
Update urllib3 to 2.0.7
Run the app and make sure it works
=> RAS-923 Update urllib3 to 2.0.7 due to vulnerability

Makefile, _infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/contexts/collection_exercise.py, response_operations_ui/templates/collection_exercise/ce-action-dates-section.html, response_operations_ui/templates/collection_exercise/ce-ci-section.html, response_operations_ui/templates/collection_exercise/ce-header-section.html, response_operations_ui/templates/collection_exercise/ce-info-section.html, response_operations_ui/views/collection_exercise.py, tests/context/conftest.py, tests/context/test_collection_exercise_context.py
This PR moves the logic from the frontend to the backend and puts in some best practises of type hinting and testing. There can be more done in this space, but I have had to be realistic what could be done in the time, in the end of the day we are populating a 3 column table, we should be able to do all the preparation in the backend to hand to a frontend to display
Elements that need to be tested.
- Edit permission - create a basic CE with an account that can, then logout and come back in with one that can't and make sure there are no links
- Check all the links are correct, i.e the text is right, edit when there is a value add when there isn't, also check they work and populate the right fields in the db
- Locking - make sure fields which should be locked, are not editable. These will …
=> RAS-315 Refactor collection-exercise

.github/workflows/codeql-analysis.yml, .github/workflows/main.yml, _infra/helm/response-operations-ui/Chart.yaml
This PR introduces codeql analysis to Rops. Also includes the Rops create release update associated with this [card](https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=planning&selectedIssue=RAS-1011&issueLimit=100) and the gcloud auth version update.
Check the code analysis output on this PR.
Check the actions build for deprecation warnings. 
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=detail&selectedIssue=RAS-1000
=> Added codeql workflow file

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/collection_exercise_controllers.py, response_operations_ui/views/collection_exercise.py, tests/views/test_collection_exercise.py
EQ v2 has been dead for some time, this removes the concept of a particular version.
General smoke test around surveys
RAS-1144
=> Remove EQ version

response_operations_ui/__init__.py, response_operations_ui/templates/messages.html
This improves the labelling around the messages filter box to aid screenreaders and voice control
Check the input field has a label with the "for" field correctly set
RAS-1365
=> DAC message filter changes

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/close-conversation.html, response_operations_ui/templates/conversation-view/cv-message-block.html, response_operations_ui/templates/messages.html, response_operations_ui/templates/secure-message/misc-inbox.html, response_operations_ui/templates/secure-message/technical-inbox.html, response_operations_ui/views/messages.py
Remove the focus from the last message in secure messaging view conversation page
Make sure when a link is produced for secure message the latest param isn't present and when clicked it still works as expected
=> RAS-1360 DAC Report - My account - Focus order

.github/workflows/codeql-analysis.yml, .github/workflows/comment.yml, .github/workflows/main.yml, _infra/helm/response-operations-ui/Chart.yaml
Pinning GHA versions to commit references
Check GHA
[RAS-1418](https://jira.ons.gov.uk/browse/RAS-1418)
**Not a production candidate**
=> RAS-1418 EPIC: Unpinned tag for a non-immutable Action in workflow

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/view-sample-ci-summary.html, response_operations_ui/views/collection_exercise.py, tests/views/test_collection_exercise.py
plug in navigation on Collection instruments 2 of 2
Make the choose a version works, and the back button on page Collection instruments 2 of 2
=> RAS-1569 Navigation to/from new 'Collection instruments 2 of 2' Page

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-ci-section.html, response_operations_ui/templates/collection_exercise/ce-sample-section.html, response_operations_ui/templates/collection_exercise/collection-exercise.html
This PR adds and updates content to the collection exercise page.
Check the updates match the acceptance criteria and figma diagram.
[RAS-1616](https://jira.ons.gov.uk/browse/RAS-1616)
=> Collection exercise page content

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-add-eq-ci.html, response_operations_ui/templates/collection_exercise/ce-eq-instrument-section.html
This PR updates the content on the step 1 of 2 CIR journey
Make sure it hits the acceptance criteria and works correctly for both CIR enabled True and False
N.B Acceptance Criteria 2 isn't possible, the way it has been implemented means a ONSInput using the searchButton key isn't possible, mainly because name isn't passed via the macro which is what we look for in the code. And because a field set is written around a ONSInput which adds a div we can't achieve it by having separate objects either (i.e input and then button)
=> RAS-1617 Collection instruments step 1 of 2 page - content
