response_operations_ui/controllers/survey_controllers.py, response_operations_ui/static/scss/base.scss, response_operations_ui/static/scss/components/info_panel.scss, response_operations_ui/static/scss/headings.scss, response_operations_ui/templates/survey.html, response_operations_ui/templates/surveys.html, response_operations_ui/views/surveys.py, tests/test_data/survey/survey.json, tests/views/test_survey.py
Added view of single survey at /surveys/<short_name>
One extra function added to the controller to retrieve required data from backstage
This backstage endpoint depends on this [PR](https://github.com/ONSdigital/ras-backstage/pull/22)
[trello](https://trello.com/c/TZoUzqkn/24-us002b-view-collection-exercises-13pts)
=> Us002b view collection exercises

response_operations_ui/controllers/collection_exercise_controllers.py, response_operations_ui/static/scss/base.scss, response_operations_ui/static/scss/components/collection-exercise-table.scss, response_operations_ui/static/scss/components/table.scss, response_operations_ui/templates/collection-exercise.html, response_operations_ui/views/surveys.py, tests/test_data/collection_exercise/collection_exercise_details.json, tests/test_data/survey/survey.json, tests/views/test_survey.py
Added a new page to show single collection exercise details.
A single call is made to backstage which returns collection exercise and survey information.
This PR uses an endpoint in ras-backstage introduced in [this PR](https://github.com/ONSdigital/ras-backstage/pull/26)
The "Shown to respondent as" field wont be filled until story US002a is complete and in an environment.
[Trello](https://trello.com/c/Gsa6v2ou/37-us003-view-collection-exercise-details-l-5-days)
[Confluence](https://digitaleq.atlassian.net/wiki/spaces/RASB/pages/160235584/US003+View+Collection+Exercise+Details+L)
=> Us003 view collection exercise details

.travis.yml
This change will cause a build only for the PR and master branch. It
stops the branch and PR being built as it's only necessary for the PR to
be built as they are effectively same things.
=> Only build branch on master

response_operations_ui/__init__.py, response_operations_ui/controllers/collection_exercise_controllers.py, response_operations_ui/controllers/collection_instrument_controllers.py, response_operations_ui/controllers/survey_controllers.py, response_operations_ui/templates/collection-exercise.html, response_operations_ui/views/collection_exercise.py, response_operations_ui/views/surveys.py, tests/test_data/collection_exercise/collection_exercise_details_no_ci.json, tests/views/test_collection_exercise.py, tests/views/test_survey.py
* User story *
As a Collection Exercise Coordinator
I need: to view the collection instruments that the system holds for the
given collection exercise
So that: I am happy that the collection instrument(s) loaded are correct
* Acceptance criteria *
Given the collection instruments have been loaded
When the user navigates to the collection exercise details page
Then they are able to see the filename (surveyid_formtype_period) of all
collection instruments that have been loaded
=> View list of collection instruments uploaded

response_operations_ui/static/scss/base.scss, response_operations_ui/static/scss/components/breadcrumb.scss, response_operations_ui/templates/collection-exercise.html, response_operations_ui/templates/home.html, response_operations_ui/templates/layouts/base.html, response_operations_ui/templates/partials/breadcrumbs.html, response_operations_ui/templates/survey.html, response_operations_ui/templates/surveys.html, response_operations_ui/views/collection_exercise.py, response_operations_ui/views/surveys.py
Added a breadcrumb trail component which is added into the top of any page which has a `breadcrumbs` variable passed to it.
The format of this variable is
```
breadcrumbs = [
{
"title": "Surveys",
"link": "/surveys"
},
{
"title": "064 QIFDI",
"link": "/surveys/QIFDI"
},
{
"title": "201803"
}
]
```
which would produce 
[Trello](https://trello.com/c/NyqftvPv/44-us026-breadcrumb-navigation-15pts-m-3-days)
[Confluence](https://digitaleq.atlassian.net/wiki/spaces/RASB/pages/174686327/US026+Breadcrumb+Navigation+M)
=> US026 Breadcrumb Navigation

Pipfile, Pipfile.lock, response_operations_ui/common/mappers.py, response_operations_ui/views/collection_exercise.py
The Java services are now consolidating the datetime format that is returned in their JSON to be more flexible but a side-effect of this is that in the main Java returns "Zulu time" using ISO8601. 
This PR adds a package for specifically parsing strings in this format (`%Y-%m-%dT%H:%M:%S.%f%z`)  and returning datetime objects. (NB: Let's not use this as an excuse to mangle things on backstage).
=> Handle date format changes services with iso8601 package

response_operations_ui/controllers/collection_instrument_controllers.py, response_operations_ui/static/js/validate-ci.js, response_operations_ui/static/scss/base.scss, response_operations_ui/templates/collection-exercise.html, response_operations_ui/templates/layouts/base.html, response_operations_ui/templates/partials/error-box.html, response_operations_ui/views/collection_exercise.py, tests/views/test_collection_exercise.py
Added client side validation of the collection instrument file type.
Added error message boxes for invalid collection instrument types and for a failed upload of a collection instrument.
[Trello](https://trello.com/c/jyN3I43Y/58-us027-validate-collection-instrument-file-format-size-medium)
[Confluence](https://digitaleq.atlassian.net/wiki/spaces/RASB/pages/230490136/US027+Validate+Collection+Instrument+s+Medium)
=> US027 validate collection instrument

response_operations_ui/templates/partials/header.html
The designs include a 3rd header bar with broad categories in them (surveys, messages, etc) but it's not on the site yet.  This includes that bar and the logic required to show which one is active.
=> Add header that's missing from the design

response_operations_ui/__init__.py, response_operations_ui/controllers/reporting_units_controllers.py, response_operations_ui/static/scss/base.scss, response_operations_ui/templates/reporting-unit.html, response_operations_ui/views/__init__.py, response_operations_ui/views/reporting_units.py, tests/test_data/reporting_units/reporting_unit.json, tests/views/test_reporting_units.py
Added new page at /reporting-units/<ru_ref>
Currently it only displays the most recent reporting unit name and the RU_REF
[Trello](https://trello.com/c/zHV82xsH/77-us044-int-view-ru-details-med)
[Confluence](https://digitaleq.atlassian.net/wiki/spaces/RASB/pages/248643696/US044+View+RU+Details)
=> Us044 display ru details

response_operations_ui/templates/collection-exercise.html
This PR adds in the ability for the user to view variable dates for a collection exercise (`employment`, `ref p start`, `ref p end`, `reminders`). 
You'll need to load in the new event dates from the RM tools to be able to view the dates.
Best to look at the qbs survey to view the dates as that all all the new variable dates added.
=> Us018 load variable event dates

response_operations_ui/templates/reporting-unit.html, tests/test_data/reporting_units/reporting_unit.json
GIVEN
The user understands which surveys the RU Ref has been selected for 
WHEN
The surveys are displayed back to the user
THEN
For each survey, the user is displayed the most recent Enrolment Code issued for that RU for that Survey
Enrollment Code displayed is based on the issued code at notification which hasn't yet been used
Once code is used and respondent is fully active and enabled suppress the code
Enrollment Code displayed is last code unused using 'Generate Code'
Dependencies: https://github.com/ONSdigital/ras-backstage/pull/55
=> View active IAC code

response_operations_ui/views/surveys.py
If a survey has no collection exercises this will cause a 500 error as collection_exercise would never be assigned from the [for loop above](https://github.com/ONSdigital/response-operations-ui/blob/remove-survey-state/response_operations_ui/views/surveys.py#L39).
=> Remove unused survey_state template variable

response_operations_ui/static/scss/components/file-picker.scss
the file picker css refers to a background image which doesn't exist, we don't actually need this bit of the css so it's been removed so we don't get 404 in the logs for every request
=> removed unused line in the file picker css to stop 404's

response_operations_ui/templates/create-message.html
There is a bug in the create message page that stops the validation error messages on the message subject from displaying properly. The HTML was picking up body errors for the subject input field, not subject errors.
This is a single line fix to make it behave as intended.
=> Fix error in validation error display in create message page.

response_operations_ui/views/messages.py
There is a bug in the messages inbox where messages sent from the 'create message' option in frontstage didn't contain the name fields it expected, causing a 500 error on loading the page.
This fixes it by taking the 'msg_to' field if the message does not have names.
=> Fix bug in secure message inbox

response_operations_ui/templates/reporting-unit.html
The calling form for creating a message in the reporting unit page wasn't wrapping it's values in string quotes. If a string had a space in, only the first word up to the space was actually getting passed through the form.
=> Bug fix: Missing string quotes in html

Pipfile, Pipfile.lock, response_operations_ui/controllers/collection_instrument_controllers.py, response_operations_ui/static/js/read-csv.js, response_operations_ui/templates/collection-exercise.html, response_operations_ui/views/collection_exercise.py, tests/test_data/collection_exercise/collection_exercise_details.json, tests/test_data/collection_exercise/collection_exercise_details_failedvalidation.json, tests/test_data/collection_exercise/collection_exercise_details_no_ci.json, tests/test_data/collection_exercise/collection_exercise_details_no_sample.json, tests/views/test_collection_exercise.py
- Get form_type from file name and upload CI using this form type classifier
- Use classifier to calculate expected CI
To test functionality:
Use classifier to calculate expected CI
1) `Make up` ras-rm-docker-dev
2) For RSI/Bricks/blocks surveys load `business-survey-sample-data.csv` sample file from `rasrm-acceptance-tests/resources/sample_files` using this response-operations-ui branch
3) The preview panel should show 5 businesses and 1 Collection Instrument (this is because CI classifier for these surveys is FORM_TYPE)
4) Do the same for BRES and you should see 5 businesses and 5 Collection Instrument in the sample preview panel.
**You may need to run this sql script because the data for BRES may not be correct:
`update ras_ci.seft_instrument`
`set file_name = …
=> Tbl133 use CI selection classifier correctly

response_operations_ui/static/js/read-csv.js
The preview panel when you select a sample file to load shows a count for expected CIs.
If you load a sample with multiple form types (Second last column) it does not show the correct count. This PR fixes this.
=> Count correct form type column

response_operations_ui/views/collection_exercise.py, tests/views/test_collection_exercise.py
Validation should fail if form type is not a digit or the length is not 4.
=> fix file name validation

response_operations_ui/static/css/override.css
Two of the columns in the messages view had unlimited widths, long business names never got cut off and caused the rest of the table to spill over the screen. 
**How to review:**
Load the messages view with a message with a very long business name (can be done by editing the HTML in browser), without this update it is unlimited and pushed other fields off the screen. This should now be limited to a reasonable width.
=> Add Width Limit to Messages View Table Columns

response_operations_ui/templates/reporting-unit.html, response_operations_ui/views/reporting_units.py, tests/views/test_reporting_units.py
User email should not be exposed in logs, as far as I know.
This PR removes the email being passed in the url (which would be exposed in the logs).
=> Remove email from url

response_operations_ui/__init__.py, response_operations_ui/views/messages.py
This PR stops the messages page from being cached by the browser. 
Testing:
Make sure all tests pass and unread messages become read when navigating back to the messages page using the back button.
=> Stop caching messages page

Pipfile, Pipfile.lock, config.py, response_operations_ui/__init__.py, tests/views/test_info.py, tests/views/test_sign_in.py
This reverts commit ea346ae1cb2b051aa11c2840e102096e466cd92a.
CSP is preventing executing inline javascript. We will need to add logic to generate and inject a nonce into the html like https://github.com/ONSdigital/eq-survey-runner/blob/b5168bb07890cefd64658f0ef0f426b810f7d3e2/app/talisman.py
=> Revert "Add security headers (#127)"

response_operations_ui/templates/change-response-status.html, response_operations_ui/templates/confirm-enrolment-change.html, response_operations_ui/templates/new-enrolment-code.html, response_operations_ui/templates/reporting-unit.html, response_operations_ui/views/case.py, response_operations_ui/views/reporting_units.py, tests/views/test_case.py, tests/views/test_reporting_units.py
Requires this branch of ras-backstage:
https://github.com/ONSdigital/ras-backstage/pull/108
The RU name should now be displayed on the 'Change enrollment status', 'Generate new enrollment code' and 'Change response status' pop up style views.
Trello card:
https://trello.com/c/1aqQQgXZ/226-change-request-add-business-names-to-pop-up-views-in-response-operations-ui
=> Add RU name to pop up style views.

Dockerfile
The working directory difference is inconsistent with the other dockerized apps in ras/rm.
Rename container working directory to `/app` to align with other apps.
Build and run container from branched Dockerfile.
Issue spotted in [hot-reloading PR](https://github.com/ONSdigital/ras-rm-docker-dev/pull/58#pullrequestreview-128273605) (compose file will also need updating).
=> Rename working directory to app for consistency

response_operations_ui/static/css/components/messaging.css, response_operations_ui/static/css/components/pagination.css, response_operations_ui/static/css/override.css
- This change tidies up the override.css file and also there is a related bug where a business name could be too long and increase the table size, pushing the date off the screen.
- Unread circle icon was removed somewhere so added back in here.
- override.css has been tidied and unused styles removed.
- messaging.css component file has been added which contains majority of messaging css.
- Manually look through different pages to see whether everything is as expected.
- Check all css is okay
=> Tidy up CSS in override.css

response_operations_ui/controllers/collection_instrument_controllers.py, tests/test_data/collection_exercise/exercise_data.json, tests/views/test_collection_exercise.py
Removes the call to backstage for linking and unlinking collection instruments.
Changes the links/unlink method in collection_exercise_controllers.py to hit the collection instrument service directly.
This also tidies up the test module to use predictable variables to use across the test methods.
Run the unit tests, make sure they pass.
Tail the logs for backstage, collection instrument service. Go to a collection exercise's detail page and select / deselect a collection instrument. Make sure backstage doesn't get the call, but collection instrument service does.
=> [TBL] Link and unlink CI's and CE's directly

response_operations_ui/controllers/survey_controllers.py, tests/views/test_message.py, tests/views/test_sign_in.py, tests/views/test_survey.py
Removes the call to backstage for listing surveys.
Changes the get_surveys_list function in survey_controllers.py to hit the survey service directly.
Run the unit tests, make sure they pass.
Tail the logs for backstage, survey service. Go to /surveys. Make sure backstage doesn't get the call, but survey service does.
=> [TBL] Call the survey service direct to retrieve list of surveys

response_operations_ui/controllers/collection_exercise_controllers.py, response_operations_ui/controllers/sample_controllers.py, response_operations_ui/controllers/survey_controllers.py, response_operations_ui/views/collection_exercise.py, tests/views/test_collection_exercise.py, tests/views/test_message.py, tests/views/test_survey.py
Removes the proxying call to backstage and ports the logic which builds a survey's details to this service.
Porting the get_survey from backstage had a knock-on effect for the various views (mostly at a test level) that rely on building and formatting everything related to a survey and its details. In other words there was more than just the survey controller that needed updating :)
=> [TBL] Get survey details direct from survey service

response_operations_ui/controllers/survey_controllers.py, tests/views/test_survey.py
Survey type has been added to the survey API when creating new surveys
to allow identification of whether the survey is Social, Business or
Census. Hardcoding the survey type to Business whilst until we've
considered how social surveys will be created.
* Passing survey type in the create survey API call
* This change should be backwards compatible so the acceptance tests should pass without the survey service changes
https://trello.com/c/ZFF7x8Za/102-dev-task-3b-int-create-action-service-to-retrieve-new-sample-attributes-13
https://github.com/ONSdigital/rm-survey-service/pull/41
No UI changes
=> Add survey type

Pipfile, Pipfile.lock, response_operations_ui/common/dates.py, tests/test_dates.py, tests/views/test_reporting_units.py
The Business have been informed that the time stamp for secure messaging doesn't reflect BST.
Time displayed for users in secure message is BST
Run RAS/RM, send a message to an internal user, the message should display the correct time
=> Output time as BST for secure message

config.py, response_operations_ui/__init__.py, response_operations_ui/controllers/case_controller.py, response_operations_ui/controllers/party_controller.py, tests/test_uaa.py, tests/views/__init__.py, tests/views/test_message.py, tests/views/test_reporting_units.py, tests/views/test_respondents.py, tests/views/test_sign_in.py, tests/views/test_survey.py
This mocks the Flask error handler so we can validate that an ApiError was raised rather than asserting false positives from other 500s.
Creates a new ViewTestCase class that the other test cases are then derived from which mocks the error handler for ApiError at setUp time.
Run the unit tests and check that we're testing everything accurately ✨🍰 ✨
=> Mock the ApiError handler to prevent false positives

response_operations_ui/controllers/collection_exercise_controllers.py, response_operations_ui/controllers/collection_instrument_controllers.py, response_operations_ui/controllers/survey_controllers.py, response_operations_ui/views/collection_exercise.py, tests/test_data/survey/classifier_type_selectors.json, tests/test_data/survey/classifier_types.json, tests/views/test_collection_exercise.py, tests/views/test_update_event_date.py
Removing proxying network requests to backstage by calling the services directly.
Change to get a collection exercise's details direct through the various services rather than proxying through the backstage service.
Big changes to the tests to accommodate the changes to how a ce details will be built.
=> [TBL] Get collection exercise details direct

response_operations_ui/controllers/survey_controllers.py, tests/views/test_collection_exercise.py
If the survey service returns a 204 (empty response) when fetching classifiers (viewing a CE) the JSON decoder raises an unexpected exception for trying to decode an empty string.  This adds more context and logging why it should fail hard (and early) when missing classifiers.
Update to the survey controller as well as a new test for 204.
Run the unit tests.  ✨🍰✨
=> Fix for guarding against an unexpected empty response from survey

response_operations_ui/controllers/collection_exercise_controllers.py, response_operations_ui/forms.py, response_operations_ui/views/collection_exercise.py, tests/views/test_collection_exercise.py
Removing proxying network requests to backstage by calling the services directly.
Change to update a collection exercise's details direct through the collection exercise service rather than proxying through the backstage service.
This also updates the form logic to fix an issue where validation would fail unless the user entered a new period.
=> [TBL] Update a collection exercise direct

response_operations_ui/views/info.py
bumping version to 0.6.1 for release
version number in info endpoint
curl the info endpoint and the version should be 0.6.1
=> bumping version to 0.6.1

response_operations_ui/controllers/case_controller.py, response_operations_ui/controllers/iac_controller.py, response_operations_ui/controllers/reporting_units_controllers.py, response_operations_ui/templates/new-enrolment-code.html, response_operations_ui/templates/reporting-unit.html, response_operations_ui/views/reporting_units.py, tests/views/test_reporting_units.py
New enrolment codes will now be generated using a case event rather than a the old POST endpoint. The UI has been updated to use this endpoint
Code now uses case event for generating new enrolment code
Can no longer generate a new enrolment code if there is an existing active one for that business/survey
`pipenv run python run_tests.py` should run tests and all pass
Run acceptance tests with associated PR's below
With associated PR's try and generate a new code through the UI and confirm that a new code is created and usable
[Trello](https://trello.com/c/npXH3s9x/16-retain-current-enrolment-code-functionality-enrolment-codes)
[case-service](https://github.com/ONSdigital/rm-case-service/pull/51)
[casesvc-api](https://github.com/ONSdigital/rm-casesvc-api/pull/21) …
=> Remove bi/generate enrolment code using event

response_operations_ui/views/messages.py
close at time in closed conversations displaying incorrect time (time in utc), this just converts it to bst before when its rendered
close a conversation should be correct time
=> Display closed at time in bst

.gitignore, response_operations_ui/views/errors.py, response_operations_ui/views/sign_in.py
Redirecting to an error page caused us issues previously when it came to tracking/diagnosing problems.
This should now allow us to receive an URL to know exactly where an issue has occurred rather then just the error page.
Card: https://trello.com/c/odV0qjxk/272-stop-redirecting-to-error-pages-in-rops-s
Ensure it now renders the correct error pages and unnecessary redirects are removed.
Just `raise exception` somewhere in the code to test it displays the error pages.
Check that all functionality works as per norm and tests pass.
=> Stop redirecting to error pages in ROps

config.py, response_operations_ui/__init__.py, tests/views/test_create_app.py
We were missing a test for when we deploy to a cloud foundry env and using its redis instance rather then the default one. 
Card: https://trello.com/c/kkO8qp4j/308-improve-rops-test-coverage-s 
Just check all tests pass and the previous untested code has been covered.
=> Added test to cover CloudFoundry set up

config.py, response_operations_ui/__init__.py, response_operations_ui/cloud/cloudfoundry.py, tests/views/test_create_app.py
This is a resurrected PR where the initial one passed locally/travis etc. but failed when it came to concourse somehow
We were missing a test for when we deploy to a cloud foundry env and using its Redis instance rather then the default one.
Card: https://trello.com/c/kkO8qp4j/308-improve-rops-test-coverage-s
Just check all tests pass and the previous untested code has been covered.
If you have access to the `dev` space in Cloud Foundry you can push this branch up and check that the app builds successfully on there.
=> Improve ROps test coverage

Pipfile, Pipfile.lock, config.py, response_operations_ui/__init__.py
Motivation and Context
==
Currently there's no way to trace the requests through the application.
What Changed
==
This will add the tracing headers to any request that comes through this
application onto another service, or preserve existing headers allowing
the user to follow requests through the application as a whole.
There are also new configuration settings:
```
| ZIPKIN_DISABLE                  | Totally disable Zipkin (including tracing headers)            | False
| ZIPKIN_DSN                      | Zipkin Sample API URL (e.g. http://zipkin:9411/api/v1/spans)  | None
| ZIPKIN_SAMPLE_RATE              | Percentage of requests to send to zipkin span API             | 0
```
By default this will add the tracing headers, but make no requests to
Zipkin's neat little UI.
How to test
==
No …
=> Zipkin Tracing

Pipfile, Pipfile.lock, config.py, response_operations_ui/__init__.py
Motivation and Context
==
Currently there's no way to trace the requests through the application.
What Changed
==
This will add the tracing headers to any request that comes through this
application onto another service, or preserve existing headers allowing
the user to follow requests through the application as a whole.
There are also new configuration settings:
```
| ZIPKIN_DISABLE                  | Totally disable Zipkin (including tracing headers)            | False
| ZIPKIN_DSN                      | Zipkin Sample API URL (e.g. http://zipkin:9411/api/v1/spans)  | None
| ZIPKIN_SAMPLE_RATE              | Percentage of requests to send to zipkin span API             | 0
```
By default this will add the tracing headers, but make no requests to
Zipkin's neat little UI.
How to test
==
No …
=> Zipkin flask

Pipfile, Pipfile.lock, response_operations_ui/views/errors.py, tests/views/__init__.py, tests/views/test_collection_exercise.py, tests/views/test_info.py, tests/views/test_message.py, tests/views/test_reporting_units.py, tests/views/test_respondents.py, tests/views/test_sign_in.py, tests/views/test_social_case.py, tests/views/test_survey.py, tests/views/test_update_event_date.py
Flask version Before 0.12.3 contains a CWE-20: Improper Input
Validation vulnerability in flask. So this PR is to update the flask
version and fix any breaking changes.
- Upgrade Flask version
- Fix breaking changes: remove mocking of error handlers and replace with asserting mock requests called
Ran Unit tests (not many of...), ITs and ATs
=> Update flask version to 1.0.2

Pipfile.lock
orderedmultidict has a new wheel associated to the same versioned app in
pypi. This causes pipenv or pip to fall over when validating the hashes
of the package are correct. Regenerating the lock file should resolve
this.
Regenerate lock file
Travis build should pass
=> Regenerate lock file

response_operations_ui/templates/collection_exercise/ce-dates-section.html
When ADD_EVENT_DATES_ENABLED is set to false the logic in the template
breaks as it is trying to find reminder2 in the events dict when
it does not exist. I have added a defensive check before so it doesn't
fall over.
ACs should run when ADD_EVENT_DATES_ENABLED is set to false
=> Fix reminder logic in template

response_operations_ui/templates/reporting-unit.html
A typo was found in the reporting unit template, where `new email` should have been
Removed typo
Change email on reporting units page and view `New Email` instead of the screen shot below
=> Fixed a typo on respondents page when an email is changed

scripts/align_events_and_rules.py
Currently action rule trigger dates and event dates do not match
in various environments. This script updates all action rules and
events. This is needed before giving the ability to moderate CE
events, using response operations, to users.
python script added
run this against your local docker dev environment:
`pipenv run python scripts/align_events_and_rules.py 
http://0.0.0.0:8145 
admin secret`
Check all events (except events for CE that are ready for live or live) have been updated and action rules in the database has been updated.
Can run as a cloudfoundry task:
`cf run-task $RESPONSE_OPERATIONS_APP_NAME "python scripts/align_events_and_rules.py $COLLECTION_EXERCISE_URL $BASIC_AUTH_USER $BASIC_AUTH_PASSWORD" --name align-rules-events`
=> Add script to align events and action rules

response_operations_ui/controllers/reporting_units_controllers.py, response_operations_ui/templates/reporting-unit.html, tests/views/test_reporting_units.py
A change was made in party service to change the resend verification email endpoint to a post this adds these changes to ROps. Also at the moment we only allow changing of response status for non-complete responses (In progress or Not started) this removes the link to change if response status is complete.
Change request to party for resend verification email to post instead of get. If response status is complete remove the link to change the response status.
I ran the acceptance tests attempted to resend verification email it worked and uploaded a SEFT so the response status is complete the change link should no longer appear.
=> Fix resend verification email and only allow change response status for non-complete

response_operations_ui/templates/edit-contact-details.html, response_operations_ui/templates/layouts/base-head.html, response_operations_ui/templates/layouts/spoke.html
External script references were referring to non-TLS connections, which causes mixed content errors in prod, and the failure of scripts to load
All template references to external scripts have been changed to use `//` prefices, rather than `https://` or `http://`, meaning that they will start to load their requirements over the protocol the page is loaded with.
* Ensure that the external dependencies load using the web tools:
* In local running
* In preprod, once there
* In prod, once there
https://github.com/ONSdigital/response-operations-ui/issues/254
=> BUG: Changed external template references to not specify protocol

response_operations_ui/templates/change-response-status.html
Without JS the hardcoded page wouldn't work. I.e. 5xx's
Use request.referrer
Disable JS and click cancel on change response status page
=> remove hard coded page and use request referrer

config.py, response_operations_ui/templates/conversation-view.html, response_operations_ui/views/messages.py
The 'close conversation' feature has been live for the last few months.  Rather than ensuring that the flag is set to 'true' in every environment, it's better practice to remove the flag altogether.
Removed the `FEATURE_ENABLE_CLOSED_CONVRSATION` flag
Secure message should run as normal and you should still be able to close conversations.
https://trello.com/c/OGBpdnXv/510-remove-closed-conversation-feature-flag-from-response-ops
=> Remove close-conversation feature flag

Dockerfile
Python Docker Images are ~1GB.  This is because of the base image.
Starting using python:3.6-slim instead
System should behave as before, acceptance tests should workfinr
https://trello.com/c/x0swxIs4/358-tbl358-review-base-docker-images
=> Change dockerfile to use smaller base image

response_operations_ui/templates/confirm-enrolment-change.html, response_operations_ui/templates/reporting-unit.html
US023 asks for the ability to re-enable enrolment in cases where it has been disabled.  This provides that
* Re-enable button added to RU view
* Re-enable button added to change enrolment view
* Pull branch
* Run response-ops and all services it relies on
* With adequate example data in place (an RU, with an enrolled respondent), ensure you can toggle the enrolment between enabled and disabled.
* Ensure acceptance tests run against this change - they have their own branch `alterations-for-us023
https://trello.com/c/StCt8X1m
=> Implementation of renablement

response_operations_ui/templates/close-conversation.html, response_operations_ui/views/messages.py, tests/views/test_message.py
When a Response-Ops UI user closes a secure message conversation, they should be returned to the inbox page they were on before they closed the conversation.
Passed through the original page the user was on. If the page no longer exists - because the final conversation on the final page has been closed - then it will redirect to the last available page. Also works if the URL is edited to go to page 999, for example.
Run the acceptance tests on the same branch.
To manually test, create enough secure messages to fill more than one page, and close a conversation - you should be returned to the page you started on.
Trello: https://trello.com/c/lCfPjUPT
=> Return user to original page when conversation closed

response_operations_ui/templates/messages.html
my conversations was showing wrong message when no conversations and in my_messages
Changed the conditional operator in messages.html to select teh correct message 
Run acceptance tests , or fire up response ops ui with no messages and navigate to my_messages
check that     'There are currently no messages' is displayed
=> Fix for no messages in my conversations

response_operations_ui/templates/conversation-view/cv-message-block.html, response_operations_ui/views/messages.py
When pressing mark unread , the user was returned to the incorrect page 
Added page to url to return to correct page , and my_conversations to go to the correct tab
Have multiple messages ( more than 1 page) .Access messages and press mark unread . Make sure it returns to correct page and tab
=> Return to page when unread

response_operations_ui/common/token_decoder.py, response_operations_ui/views/errors.py
The unit tests had over 100 warnings when run.  This reduces it down to 5.
- Run the unit tests (`make test`) and the python tests should have 5 warnings.
=> Fix majority of test warnings

response_operations_ui/common/token_decoder.py
Fixes the warning fix from earlier.   For now we can live with the deprecation warning during the unit tests as changing it to be correct causes the unit tests to fail in a 'non-trivial to fix' way.
- Fire up this service and attempt to sign in.  You should no longer see an error ending in `raise InvalidAlgorithmError('The specified alg value is not allowed')\njwt.exceptions.InvalidAlgorithmError: The specified alg value is not allowed"`
=> Use correct algorithm for uaa jwt

.mocharc.json, gulp/tasks/csslint.js, gulp/tasks/test.js, gulp/tasks/watch.js, gulpfile.js, package-lock.json, package.json, response_operations_ui/assets/tests/example_test.test.js, response_operations_ui/assets/tests/example_test_functions.js
Added a Javascript testing framework (Jest) to allow us to start covering Javascript used on the frontend (currently not covered).
* Installed Jest
* Added Jest Gulp task
* Added test to NPM
* Added test to Gulp 'test' and 'watch' functions
* Wrote example test file to help explain tests to users
* Remove `.skip` as per comment in example test file.
* Run jest tests to confirm they run (run `npm test`, `npm run gulp test`)
* No acceptance tests involved
https://trello.com/c/8Mc2jeAx
=> Add js testing framework

tests/test_logger_config.py
There was a warning in the logger config unit tests that wasn't fixable by us (as the problem is in the library).  Suppressing the warning is reasonable here (where it rarely is okay) because it's being left there intentionally to be backwards compatible with Python 2.
The warning is suppressed in the logger config tests.  This suppression doesn't affect any other warnings.
Unit tests should still pass
=> Suppress testfixtures warning

response_operations_ui/templates/create-ce-event.html, response_operations_ui/templates/update-event-date.html
A previous PR updated the version of the pattern library.  One of the unnoticed things that broke was the formatting of the dates on the create/change business events page.
Just the HTML to deal with the layout of the date box.
Additionally, the labels on the affected have their `for` attribute configured correctly now, so clicking on the label will select the input box.
Look at the create and change business events pages 
- Surveys -> Pick a survey -> Create collection exercise (Create page)
- Surveys -> Pick a survey -> Pick a collection exercise -> edit one of the top left fields (Update page)
https://trello.com/c/Bdu8EYTp
=> Fix styling on date fields

response_operations_ui/common/respondent_utils.py, tests/common/test_respondent_utils.py
Was causing 500 errors when clicking on a respondent
Added the /respondents/ route to links
search for a respondent and click on a result, shouldn't error
https://trello.com/c/M8esqZzO/855-bug-when-finding-a-respondent-by-search-in-resops-clicking-on-the-link-to-their-profile-causes-a-500-error
=> added route to respondent links

Pipfile.lock
Jinja 2.10 has a security issue.  This is fixed in 2.10.1.  This PR updates jinja and a number of other packages by virtue of `pipenv update`
Hopefully nothing other then the version of packages we're using
Unit and acceptance tests should still pass.  Nothing else should've changed.
It's important that this is tested in the reviewers local environment as there's a chance that one reviewer could catch something that another did not.
=> Update packages to fix jinja security issue

gulp/tasks/scsscompile.js, package-lock.json, package.json
Pipeline had broken due to a reliance by an NPM package (`gulp-sass`) on a no-longer-existent binary hosted on Github.
Have moved to a non-compiled version, because there is a current security advisory to do with the `tar` package, which is pinned by `node-gyp`.  To mitigate this, I have taken out compiled steps from the NPM packages, so that `node-gyp` will not be used.
Once `node-gyp` address their reliance on `tar` @2.2.8 (current version is 4.4.8, and is the first that removes the vulnerability), we can consider using compiled bindings.
* `node-sass` module removed
* `sass` module (dart-sass) added
* `sass` specified as `gulp-sass` compiler
* `fibers` module used to speed up compilation loss.
Ensure that you can still run gulp tasks, particularly `scss`, and `build`.
Ensure that you …
=> Removed reliance on node-sass and swapped to dart sass

response_operations_ui/__init__.py, response_operations_ui/assets/tests/read-csv.test.js, response_operations_ui/static/js/read-csv.js, response_operations_ui/templates/collection_exercise/ce-sample-section.html
Read CSV changes inadvertently broke cancel button due to a namespacing error.  fixed.
References to wrong named function changed.
Added condition to JS bundler to avoid issue with map files.
Fire up the resops app, select a CSV for sample upload, ensure cancel button now works.
https://trello.com/c/jmdo0wNE
=> Bug fix: Namespacing error

response_operations_ui/assets/tests/validate-ci.test.js, response_operations_ui/static/js/validate-ci.js
Previously, when a user selects an eq collection instrument file on a survey in response operations ui, the button to add the collection instrument would stay grey, and the mouse cursor would tell the user that the button cannot be pressed, even though the user actually can press the button. This PR adds a line of code to make the button turn green and to tell the user that it can be pressed.
* Added a line of code in validate-ci.js to change the button's displayed colour when a valid collection instrument is selected.
* Adjusted the code in the validate-ci.test.js file so that the tests for showing/hiding the panel based on whether or not the file type is correct expect the right values.
* On response operations ui (localhost:8085), log in, then go "surveys", then click on a survey, then …
=> fixed error to make sure button turns green

response_operations_ui/controllers/party_controller.py, response_operations_ui/views/respondents.py, tests/views/test_respondents.py
Selecting page 1 of pagination leads to a 500
Changed the default page to be page 1 ( there was not one previously, which led to the issue) . Added unit test, did a small boy scout change of function name to reflect its internal only use
Run unit tests
Run up response ops , do a search with email of '@' to get all, then select page 2 then page 1 . Previously this would lead to a 500
https://trello.com/c/pkNdz56p
=> 1005 respondent pagination bug fix

response_operations_ui/forms.py, response_operations_ui/templates/collection_exercise/ce-reference-information.html, response_operations_ui/templates/edit-collection-exercise-details.html
Remove edit capability from the user description of a collex, because editing it doesn't work
Edit button removed
Edit field removed and replaced with hidden field
Markup changed to only feature one visible field
Spin up resops, ensure you can create a collex, but only edit the period, not the 'period the user sees'.
Make sure tests pass.
https://trello.com/c/aYtYMH8O
=> Remove edit from user period ce

response_operations_ui/templates/reporting-unit.html
Business previously had to make service desk requests to changes to CE's from more than 4 months ago
System was already pulling all the surveys and limiting the display in the template to the most recent 4, increased it to 12. (no performance difference)
After running the AT's you can add this line on a local running resops on line 55 in reporting_units.py to get 12 surveys loaded:
sorted_linked_surveys[0]['collection_exercises'] = sorted_linked_surveys[0]['collection_exercises'] * 6
https://trello.com/c/ocsILSfS/1068-12-months-on-response-ops-for-ces-5
=> Increase number of CE's shown on RU page to 12.

config.py, response_operations_ui/templates/layouts/base-head.html
ras-frontstage has google analytics but response-operations doesn't.  We're adding it so that we can start seeing the journeys that internal users take though our systems so we can have more data to figure out what's important.
Added google analytics code snippet
Can't be tested until it hits preprod.  We've added the container value (the GOOGLE_ANALYTICS value) into the preprod build.  Once we've deployed it and verified the analytics are working, we'll need to do the same to prod
https://trello.com/c/A9wl7wX5/794-add-analytics-to-rops-iv5
=> Add google analytics

response_operations_ui/templates/messages.html, response_operations_ui/views/messages.py
A new tab was requested that only showed new conversations initiated by respondents
New tab added , along with changes to calls to secure message to restrict by new messages from respondent for this tab
Either run the acceptance tests , or have frontstage and response ops running and fire in messages from respondent and validating they appear on the new tab labelled 'Initial' Once responded to they do not appear here . Also conversations initiated by the internal person do not appear on this tab
https://trello.com/c/G1PNU5Qa
=> added initial conversations tab

response_operations_ui/controllers/case_controller.py, response_operations_ui/controllers/party_controller.py, response_operations_ui/views/case.py, response_operations_ui/views/reporting_units.py
There are a few places we use the ru_ref and don't log it.  This is useful because the business generally give us an ru_ref as the only piece of information when something goes wrong.
A few log lines have been added, and a few log lines have had ru_ref added to the metadata
Unit tests pass
=> Add ru_ref metadata to a number of log lines

.travis.yml, config.py, response_operations_ui/__init__.py, response_operations_ui/templates/layouts/base.html, response_operations_ui/templates/partials/header.html, response_operations_ui/views/info.py, tests/views/test_availability_message.py
Currently when we do a deploy  we don't  put maintenance banner when we work on response ops.Mostly this is handled by pre-communication with the business but this limits times we can do deployments and potentially causes issues if someone is in the middle of a session.
We need a better strategy for managing response ops downtime.
Few lines of code added  :
To access  redis  new decorator variable session .
Modified Partials/header.html as well to add availability msg variable
Added new test file which include Unit test cases to test the fix .
Manual and unit test passed
https://trello.com/c/WGSjK35Y
=> Maintainance banner res ops ui

response_operations_ui/templates/layouts/base.html, response_operations_ui/templates/partials/header.html
Currently when we do a deploy we don't put maintenance banner when we work on response ops.Mostly this is handled by pre-communication with the business but this limits times we can do deployments and potentially causes issues if someone is in the middle of a session.
We need a better strategy for managing response ops downtime
Modified Partials/header.html  and templates/layouts/base.html  to correct banner postion  a
tested manually  and passed the test 
https://trello.com/c/WGSjK35Y
=> html changes to correct banner postion

response_operations_ui/controllers/uaa_controller.py, response_operations_ui/templates/reset-password.html, response_operations_ui/views/passwords.py
UAA throws a non-200 (422) if you try to set your new password to what it was before. I was handling all non-200s in the same fashion ("Something went wrong" page) but that's obviously overkill here, so it uses the form errors system to display a nice message instead
=> Better error handling when new password matches old one

response_operations_ui/forms.py, response_operations_ui/templates/edit-contact-details.html
Bug found where the error messages were not displaying for email and telephone.
Added in the error message for no telephone and fixed the type of email address. Removed redundant code.
Spin up response ops manually, go to edit details page, inspect and remove the required tags, submit a form with blank text boxes.
https://trello.com/c/T4mEeKr3
=> remove redundant code and modify error messages

response_operations_ui/templates/layouts/base.html
We're having weird 404s in the logs for the main.min.js.map missing in prod.  It's possibly caused by a mixed-content error happening when the site tries to get jquery as it's over http (and maybe the main.min.js is being served over https?).  Regardless of whether this fixes the problem, this should stop this particiular error occuring and we should always be communicating over https wherever possible.
=> Upgrade jquery retrieval from http to https

response_operations_ui/views/messages.py, tests/test_data/message/thread.json, tests/test_data/message/thread_missing_respondent.json, tests/test_data/message/thread_missing_subject.json, tests/test_data/message/thread_unread.json, tests/test_data/message/threads.json, tests/test_data/message/threads_missing_atmsg_from.json, tests/test_data/message/threads_missing_atmsg_to.json, tests/test_data/message/threads_missing_business_name.json, tests/test_data/message/threads_missing_msg_to.json, tests/test_data/message/threads_missing_ru_ref.json, tests/test_data/message/threads_missing_sent_date.json, tests/test_data/message/threads_multipage.json, tests/test_data/message/threads_no_unread.json, tests/test_data/message/threads_unread.json
In secure-message, we're changing ru_id to business_id to more accurately reflect what it is.  This required us changing the @ru_id part of the payload to a more sensible name.  Instead of @business_id, it's been changed to @business_details as it doesn't only include the id so it's more accurate.
- All instances of @ru_id have been changed to @business_details
- Everything works as it did before.  Unit and acceptance tests still pass
https://trello.com/c/nct0vF5E
=> Rename @ru_id to @business_details

response_operations_ui/templates/collection_exercise/ce-header-section.html, response_operations_ui/templates/collection_exercise/ce-instrument-section.html, response_operations_ui/templates/collection_exercise/ce-sample-section.html, response_operations_ui/templates/conversation-view/cv-reopen-form.html, response_operations_ui/templates/conversation-view/cv-reply-form.html, response_operations_ui/templates/create-message.html, response_operations_ui/templates/forgot-password.html, response_operations_ui/templates/message-select-survey.html, response_operations_ui/templates/reporting-unit-search/reporting-units-search.html, response_operations_ui/templates/reporting-unit-search/reporting-units.html, response_operations_ui/templates/reporting-unit.html, response_operations_ui/templates/reset-password.html, response_operations_ui/templates/respondent-search/respondent-search.html, response_operations_ui/templates/respondent-search/rs-inline-form.html, response_operations_ui/templates/sign_in.html
Issue with forms being submitted multiple times due to multiple button clicks.
Design system button component has an attribute available that runs some JS that disables the button after being clicked for a couple of seconds. This prevents the double click scenario but allows the button to become clickable again in the event something goes wrong (with the back end response).
Check that buttons work as they should and prevent double click. Sign in page is a good example.
=> Added timer attribute to all buttons to prevent double submit

response_operations_ui/templates/components/upload/_macro.njk
The upload component in the design system had the `attributes` param removed.
This PR puts it back so load sample works again.
Check you can load a sample ok.
=> Upload component had attributes param removed

response_operations_ui/views/respondents.py, tests/test_dates.py
As it currently stands a search for a respondent uses a POST request that redirects to a GET request, in order to pass the parameters from the form data the request appends the first name, last name and email to the get request as url parameters.
Instead let's render the template on POST request as it has all the data it needs at that point anyway.
Modified the respondents.py file and removed the redirection.
Start the respondent operations UI and attempt to search for a user by email. This functionality should continue to work but the inputted data is no longer in the url. 
https://trello.com/c/rnMDzAee/1423-stop-email-address-being-passed-as-a-url-parameter-in-rops-3
=> Render template on POST

response_operations_ui/templates/components/lists/_macro.njk, response_operations_ui/templates/errors/500-error.html, response_operations_ui/templates/reporting-unit-search/reporting-units-search.html, response_operations_ui/templates/reporting-unit-search/reporting-units.html, response_operations_ui/templates/respondent-search/respondent-search-results.html, response_operations_ui/templates/respondent-search/respondent-search.html, response_operations_ui/templates/respondent-search/rs-inline-form.html, response_operations_ui/templates/respondent-search/rs-table.html, response_operations_ui/templates/respondent.html
Refactored a set of remaining templates in r'ops to use design system macros correctly.
- 500-error.html
- reporting-units-search.html
- reporting-units.html
- respondent-search.html
- respondent-search-results.html
- rs-inline-form.html
- rs-pagination.html
- rs-table.html
- respondent.html
Ensure pages and workflow is correct.
Ensure acceptance tests pass.
=> Refactor remaining templates

response_operations_ui/templates/conversation-view/cv-message-block.html
Issue where any line breaks added to an SM reply were not displayed in the message thread.
Added a `white-space` attribute to maintain the formatting
Send a message that has line breaks and check that this is maintained in the thread.
=> Fixed issue with whitespace on sm reply

response_operations_ui/controllers/case_controller.py, tests/controllers/test_case_controller.py
Resolves https://trello.com/c/e5mHbNx8/1484-ritm0307110-re-instate-deleted-account-15-01-20
if they have no enrolments then they should not see any, but instead they are getting a 500 response. This is because the 204 response code lives within a catch block and given that a 204 is a valid response then response.raise_for_status() never throws. The code attempts to json parse nothing which throws the 500 that they are seeing.
try to view enrolments for respondent with no enrolments. you used to get a 500, now you get a screen with no enrolments
https://trello.com/c/e5mHbNx8/1484-ritm0307110-re-instate-deleted-account-15-01-20
=> No enrolements

Makefile
Disabled 'pipenv check' in Makefile, pending resolution of blocking pipenv bugs 2412 (plus duplicates) and 4147 
Commented the line 'pipenv check' in the Makefile, with a note to uncomment as soon as possible.
make build
make lint
https://trello.com/c/botlRPsE
=> temporarily disabled pipenv check, pending pipenv bug resolution

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/backendconfig.yaml, config.py, response_operations_ui/__init__.py
When running behind a GCP load balancer with SSL termination use the HTTP_X_FORWARDED_PROTO header to set the protocol scheme on the WSGI middleware.
If this is not set then flask will redirect all requests back to http.
=> Add fix for load balancer ssl termination in GCP

_infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml
To allow the docker image to be specified in spinnaker
Docker image tag defaults to AppVersion but can now be overwritten.
=> added image.tag to helm templates

_infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml
The helm charts needed to have the option of selecting different repos when a developer is testing changes.
- The `deployment.yaml` now switches to the devRepo if the `latest` tag is not set.
- Added the devRepo to `values.yaml`. As of now, it is the same as the current image's repo, but will be different in prod and pre-prod.
[Trello card](https://trello.com/c/fLbRN0qG)
=> added devRepo

_infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml, config.py, response_operations_ui/common/validators.py, response_operations_ui/views/sign_in.py
To help us test creating collection exercises, we needed to have a flag that is set to false by default, but allows testers to set it to true to allow past dates.
Added a `TEST_MODE` flag to `config.py`
Go to `config.py` and set `TEST_MODE` from `false` to `True`.
Create a collection exercise in response-operations-ui, then click on the link for the new collection exercise and then add MPS. There, try to enter a date in the past, and it should allow it. Conversely, if `TEST_MODE` is set to `False`, it won't.
[Trello card](https://trello.com/c/X7ZRA02H)
=> added flag for allowing past dates

response_operations_ui/templates/collection_exercise/ce-instrument-section.html, response_operations_ui/templates/collection_exercise/ce-sample-section.html
More CSRF tokens missing.  Will try and get the sample file upload error in this PR too as it's partially a CSRF tokens issue and partially a javascript issue
Update: Contains the CSRF fix for the sample file but not the javascript part.  That will come in a separate pull request
=> Fix missing csrf token for collection instruments

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/logger_config.py, tests/test_logger_config.py
Added "severity level" processor to structlog, so Google Cloud Logging can parse the severity
New structlog processor defined in logger config, replacing obsolete zipkin processor
Unit tests updated for the change
make test, or
pipenv run python run_tests.py
Spin up cluster in Dev, with response ops pod built from image tag "cloud-logging-new"; generate an error by reqesting non-existent survey ID MBX; check Stackdriver logs for correct parsing and severity levels.
https://trello.com/c/wDSxYgCQ
=> New structlog processor for Google Cloud Logging

response_operations_ui/views/respondents.py
When the search page loads, the path is:
http://localhost:8080/respondents/
After a search is made, this redirects to the results page:
http://localhost:8080/respondents/search
If the user reloads the page, or navigates back to it from a second page of results, the former 500 error (with no navigation visible) is replaced with the much friendlier and more usable error of:
"At least one input should be filled", in
http://localhost:8080/respondents/
Added a GET method to the Flask route for respondent search, alongside the POST used for actual searches. No refactoring has been done. 
Local: 
- pipenv run python run_tests.py
- Spin up a local cluster, log into the surveys page on localhost:8085, search for a respondent, and reload the search results page.
Dev: 
- Spin up a cluster, with …
=> fix route method for respondent search

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml
The overview screen uses the dashboard but in preprod/prod the dashboard is behind an ingress so the the usual way of getting the address must be modified slightly.
=> add dashboard config if it has an ingress

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/home.py, tests/views/test_home.py
When completed was 0, it would default to displaying N/A instead of 0.  This change makes it so that if the sample size is 0, it displays '0 (0.0%)', otherwise it displays the completed number and the percentage.
=> Fix bug when completed = 0

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/party_controller.py, tests/views/test_reporting_units.py, tests/views/test_respondents.py
Fix for https://collaborate2.ons.gov.uk/jira/browse/RAS-40, where in testing whitespace was stripped from the form during contact update (https://github.com/ONSdigital/response-operations-ui/pull/510) but not from the updated email pushed to Party service.
Added strip() of email to update_contact_details in party controller.
Same as last pull request https://github.com/ONSdigital/response-operations-ui/pull/510, but this time actually check for spaces in the database with `SELECT * FROM partysvc.respondent;`.
=> strip whitespace at update to party controller

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/collection_instrument_controllers.py, response_operations_ui/views/collection_exercise.py, tests/controllers/test_collection_instrument_controller.py
For ru specific SEFT uploads, there is now a bit of validation with specific error text.  This PR allows that specific text to be rendered on screen if present, whilst falling back to default error text if there's nothing to put up.
=> Use error text from api if provided

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/forms.py, response_operations_ui/templates/conversation-view/cv-reply-form.html, response_operations_ui/templates/create-message.html
The message body character limit needed to be increased to 50000 from the previous 10000.
* Message body now allow messages of up to 50000.
Send a message of between 10000-50000 characters, and make sure it validates correctly
[Jira card](https://collaborate2.ons.gov.uk/jira/browse/RAS-16)
[Related frontstage PR](https://github.com/ONSdigital/ras-frontstage/pull/617)
[Related secure-message PR](https://github.com/ONSdigital/ras-secure-message/pull/308)
=> changed message body character limit to 50000

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-instrument-section.html, response_operations_ui/templates/survey.html, response_operations_ui/views/collection_exercise.py, response_operations_ui/views/surveys.py, tests/test_data/collection_exercise/formatted_collection_exercise_details.json, tests/test_data/collection_exercise/formatted_collection_exercise_details_failedvalidation.json, tests/test_data/collection_exercise/formatted_collection_exercise_details_no_ci.json, tests/test_data/collection_exercise/formatted_collection_exercise_details_no_events.json, tests/test_data/collection_exercise/formatted_collection_exercise_details_no_sample.json, tests/test_data/collection_exercise/seft_collection_exercise_details.json, tests/test_data/survey/ashe_response.json, tests/test_data/survey/edited_survey_ce_details.json, tests/test_data/survey/survey_by_id.json, tests/test_data/survey/updated_survey_list.json, tests/views/test_message.py
Until the surveyMode was added for a survey, we had to add hardcoded lists of known EQ and SEFT surveys as a temporary solution.  Now that the surveyMode has been added, this PR removes the temporary lists and uses the supplied surveyMode data
=> Remove hardcoded lists and check surveyMode instead

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/deployment.yaml, config.py, response_operations_ui/controllers/respondent_controllers.py, response_operations_ui/templates/delete-respondent.html, response_operations_ui/templates/respondent-search/respondent-search.html, response_operations_ui/templates/respondent.html, response_operations_ui/views/respondents.py, tests/views/test_reporting_units.py, tests/views/test_respondents.py
This PR provides a new feature to mark respondent user account ready for deletion with the next processing and to undo the deletion.
> * New html included as per the prototype
> * New endpoints to `respondent.py`
> * Changes to `respondent_controller.py`
> * Changes to existing view
Smoke Test
[Trello](https://trello.com/c/eg9lY2nj/12-s20-gdpr-retention-manual-account-deletion-process-following-respondent-request-8)
=> GDPR Account Deletion

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/backendconfig.yaml, _infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml, response_operations_ui/__init__.py
With the kubernetes upgrade response ops ui is failing for x forward proto not supported. This PR contains the fix for the same.
X-Forward-Proto has been removed and a schema has been introduced for referance.
Smoke Test
=> Changes to fix the issue with X-Forward-Proto not supported

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/party_controller.py, response_operations_ui/views/reporting_units.py, tests/test_data/party/respondent_party_list.json, tests/views/test_reporting_units.py
Previously, for the reporting unit page it would get each respondent from party one by one.  This PR makes it get them all in one go.  There is a slight performance increase for doing this (on a sufficiently large reporting unit I saw up to a 25% improvement, going from 4sec to 3 seconds) and the logging becomes less noisy (2 log lines instead of 2 x number of respondent log lines).
Go to a reporting unit and make sure the respondent data looks like it always does.  This PR shouldn't have any noticeable changes for the user.
=> Get respondents in a single call, rather then many

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/reporting_units.py, tests/test_data/case/cases_list_completed.json, tests/views/test_reporting_units.py, tests/views/test_respondents.py
The reporting unit page was making 2 calls, one to get case data and the other to get casegroup data.  The former contains the latter, so this PR makes it so theres only 1 call needed.  This should result in less communications between the systems, and a very minor performance boost (in the tens/hundreds of ms).
Open a reporting unit page and see that all the expected data is there.  This PR shouldn't be noticable to a user of the system.
=> Remove casegroups call

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/party_controller.py, tests/controllers/test_party_controller.py
If a reporting unit had no respondents associated with it, it would cause an error due to it calling party with an empty list.
This PR fixes that
=> Fix error when party list is empty

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/templates/external-secrets.yaml
We cannot use the uaa-secret to get the client-id and secert as that contains a giant yaml file.
=> put client-id and secret in rops external secret

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/party_controller.py, response_operations_ui/views/reporting_units.py, tests/views/test_reporting_units.py
There was a bug where if a reporting unit was part of more than 50~ collection exercises, the url for the search would be too long and get rejected by gunicorn.  This PR makes it so that it gets ALL the attributes and then filters out all the non-live collection exercises (of which there should only be a handful).
=> Modify how attributes come from party

response_operations_ui/views/messages.py, tests/views/test_change_response_status.py, tests/views/test_message.py, tests/views/test_reporting_units.py
rOps users needed to be sent back to the reporting unit page after sending a message, because it's tedious having to navigate back after it sends you to the message thread list.
The `/create-messages` endpoint now redirects the user back to the previously selected responding unit page after a message is sent.
On response-ops, find a reporting unit, click on a survey, find a respondent, and click create message. Then, type in a message and send it. It should redirect you back to the reporting unit page.
[Trello card](https://trello.com/c/XrN8aya6)
=> changed redirect after message

tests/common/test_data/closest_future_collection_exercise.json, tests/common/test_data/closest_past_collection_exercise.json, tests/common/test_data/mixed_past_and_future_collection_exercises.json, tests/common/test_data/multiple_same_start_collection_exercises.json, tests/common/test_data/only_future_collection_exercises.json, tests/common/test_data/only_past_collection_exercises.json, tests/common/test_data/single_new_collection_exercise_for_survey.json, tests/common/test_filters.py, tests/common/test_mappers.py, tests/controllers/test_case_controller.py, tests/controllers/test_collection_exercise_controller.py, tests/test_validators.py, tests/views/test_change_response_status.py, tests/views/test_collection_exercise.py, tests/views/test_data/closest_past_collection_exercise.json, tests/views/test_home.py, tests/views/test_message.py, tests/views/test_reporting_units.py, tests/views/test_respondents.py, tests/views/test_survey.py, tests/views/test_update_event_date.py
Before the only decent way to run the majority of the tests was to `make test`, this change makes the tests smarter about finding test data relative to where the test is being run. This means you can run an increased number of them individually (via pycharm or whatever else) as opposed to being forced to sit through the whole suite.
=> Improve test running

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/respondent_controllers.py
Changes to make sure if the respondent delete is initiated from response operation UI it is forced.
delete respondent, login via frontstage and test its still deleted once picked up via scheduler
https://trello.com/c/8Lt4wbOX/632-bug-respondent-delete
=> changes to incorporate additional flag added to auth.user table

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/collection_exercise.py
The time of sample ingest on the collection exercise screen hasn't been modified for DST
Ingest a sample and confirm that it shows the time in UTC+1
https://trello.com/c/8VBq10kX/628-bug-sample-uploaded-timestamp-in-response-ops-is-off-by-an-hour
=> Properly localise the sample ingest time on a Collection Exercise

Pipfile, Pipfile.lock, _infra/helm/response-operations-ui/Chart.yaml
Software package no longer required
Load in the environment
S32 Remove codecov package use from python repos
=> remove reference to codecov

.github/workflows/main.yml, _infra/helm/response-operations-ui/Chart.yaml
During the release step tag the generated docker image as both the release version and latest.
=> Docker tag latest at the same time as the release

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/create-ce-event.html, response_operations_ui/templates/update-event-date.html, response_operations_ui/views/update_event_date.py
Ref period start, Ref period end and employment date are date fields rather than datetime fields. This PR stops the user being able to set the time element.
Set up a CE and check that the time field is not displayed for the fields ref period start, ref period end and employment.
Once set up check, repeat the same check for updating the fields.
https://trello.com/c/IRR0NUpx/666-bug-ritm0581287-this-is-now-sorted-but-need-to-query-how-the-reference-period-start-date-is-picked-up-by-eq-there-is-an-issue-wi
=> Removing time from ref period start and end dates

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/reporting-unit-survey.html, response_operations_ui/templates/reporting-unit.html, response_operations_ui/views/reporting_units.py
Fixes both the survey ordering in the reporting unit page (was ordering on the survey's hidden uuid rather then the displayed  reference number (009, 023, etc) and the broken resend verification url link (the ru_ref wasn't being set correctly)
=> Fix table ordering

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/reporting_units.py
There's an issue with the new hub-and-spoke design where the details aren't necessarily being taken from the newest collection exercise. This is due to a bug with the data structure used to build the table.
=> Fix period changing

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/reporting_units.py
Respondent names aren't currently alphabetised on the new respondent page in the hub and spoke, and the business would prefer they were.
Have a business with >1 respondent and check they're in alphabetical order
https://trello.com/c/uNgcm23w/738-rops-overhaul-reporting-unit-hub-and-spoke-design-iteration
=> Alphabetise respondents

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/messages.py
This PR changes bits of the functionality around changing a message category.  It now takes you back to the inbox you were on, rather then back to the message you just changed.
It also marks the thread as unread in the new inbox.
=> Change message category amendments

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/party_controller.py, response_operations_ui/views/messages.py, tests/views/test_message.py
If you have a thread that starts as a survey, gets changed to technical/misc, do some more replies, then try and close it, a 500 error would occur.  This is because the most recent messages don't have survey data in them and the `_refine` function used to always assume you'd have something.
=> Fix close category in a technical context

Makefile, _infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/messages.py, tests/views/test_message.py
If the respondent initiated a secure message, either via the something else help on "my account" or "help with this survey", then when the conversation was being closed the respondent was incorrectly shown as the ONS user. This was because external messages were incorrectly using the "to" field of the refined thread, rather than the "from" field.
Port-forward to dev cluster, and run make test locally on Frontstage. (Or `/deploy` from here to your dev cluster.)
In Frontstage "To-do", click "Get help with this survey" to send a new message. In rOps,  open the new message, and click "Close conversation". In the "Close conversation" dialogue, Respondent should now be correct. On the default data loaded from Acceptance tests, the pre-loaded survey will be "QBS", and the respondent will be …
=> Respondent close conversation

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/reporting_units.py
There was an issue where the verification email link for a pending account wasn't working. This was because the function that was meant to be called was moved to a different class. This PR fixes this, as well as adds a check for the pending status via the Flask form so that the `is_new_account_verification` Boolean can be set to true.
Create a new user and, for a survey that is pending enrolment, click the link to resend the verification e-mail, then click the green button. It should work. You may also want to test it out when a respondent has initiated an e-mail change, but before the respondent has verified it.
[Card](https://trello.com/c/LY9PGt49)
=> fixing verification email bug

Makefile, _infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/reporting-unit-respondents.html, response_operations_ui/templates/reporting-unit.html, response_operations_ui/views/reporting_units.py, tests/test_data/case/cases_list.json, tests/views/test_reporting_units.py
One of the things that impacted the performance of the page was that it resolved that data for EVERY collection exercise for EVERY case the business was ever part of.  This change makes it only resolve every collection exercise for every case that is related to the survey on the page we're on.
Testing it with a reporting unit that has a massive data set, it went from ~18 seconds to ~10 seconds which is a respectable difference (though still awful in the grand scheme of things, but one improvement at a time!)
=> Improve performance of reporting unit survey page

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/uaa_controller.py, response_operations_ui/templates/account/my-account.html, response_operations_ui/templates/layouts/base.html, response_operations_ui/views/accounts.py, tests/test_data/uaa/user_by_id.json, tests/views/test_accounts.py, tests/views/test_sign_in.py
This is the basis for the new 'my account' page in response ops.  This includes a page that displays the data held on an internal user in uaa.  It also moves the sign out link to the top header instead of the middle header.
Note:  This PR doesn't include the link to the page and aborts as soon as you try and use it.  This will be removed and the page 'switched on' in a following story once we have the ability to change any of those details.
=> Add my account page

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/account/change-account-name.html, response_operations_ui/views/accounts.py
Making sure that an email is sent before the user is updated to keep in line with IA requirements. 
https://trello.com/c/fj13gJEo/1361-rops-ui-self-service-change-name-email-sending-failure
=> Change email validation and user update order

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/__init__.py, response_operations_ui/controllers/collection_exercise_controllers.py, response_operations_ui/controllers/party_controller.py, response_operations_ui/controllers/sample_controllers.py, response_operations_ui/views/collection_exercise.py, tests/controllers/test_party_controller.py, tests/views/test_collection_exercise.py
Currently, when a sample is deleted from a collection exercise, it's only unlinked in collection exercise and the data that gets created in party and sample is simply orphaned.  This PR will call the 2 newly created DELETE endpoints to clean up the data as well doing this unlinking
- Create a collection exercise in response ops
- Load a sample for it.  Verify records are created for it in sample (sample_units and sample_summary), collection exercise (sample_links) and party (business_attributes) database tables.
- Delete the sample. 
- Verify that those records have been deleted in all 3 places
=> Properly delete sample when removed from a collection exercise

Pipfile, Pipfile.lock, _infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-sample-ci-section.html, response_operations_ui/templates/collection_exercise/ce-sample-section.html, tests/views/test_collection_exercise.py
At the moment, if the sample is in the process of being loaded, the `ingestDateTime` value is `None` which causes a 500 error since one of the tables is trying to subscript a NoneType. This adds a check to ensure that the sample upload date time is only being accessed once the sample is fully loaded.
Go into the database and change the `state_fk` column in the `sample_summary` table between `INIT`, `ACTIVE`, `FAILED` and `COMPLETE`, to check that none of the states cause an error.
https://trello.com/c/i1CkfY6p/1739-500-on-rops-when-sample-is-being-loaded-causing-acceptance-tests-to-fail
=> Fixing collection exercise page to deal with sample load error

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/collection_exercise.py
When there's an issue with the sample file not caught by the validator, the Sample File Uploader currently throws a 400 or 500. This handles 400s in a better way, bubbling up the message sent to us by the uploader (which should be fine to show to an internal user, e.g. `"Too few columns in CSV file"`)
https://trello.com/c/HjIMIYwj/1757-bug-500-raised-when-uploading-a-sample-with-less-than-the-required-columns-track-time
=> Better error handling for sample file problems

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/admin/manage-account.html
There was a small design iteration needed for the edit user permission page.  This PR adds a purely visual 'view' checkbox against each category so it's clear to the user that the smallest amount of permission still allows viewable records
- Build enviornment
- Run acceptance tests to seed data
- Add the users.admin permission to the 'uaa_user' (in public.groups find the permission, copy the uuid then create a new row in the public.group_membership table for that user for that group) to make the 'manage user accounts' link appear.
- Go to the edit user page and verify that it looks like the design in the attached trello card.
https://trello.com/c/78qGT2X1
=> Add view checkboxes for visual clarity

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml, config.py
When we removed the feature flag for the eq v3 work, we removed the flag from the code, but forgot to remove it from the helm chart.  This PR removes the remaining config for it.
=> Remove EQ_VERSION_ENABLED flag

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/uaa_controller.py, response_operations_ui/views/admin/manage_user_accounts.py, tests/views/test_admin.py
Having a method return >1 type is confusing and a pretty quick way to get errors
https://trello.com/c/po2v9sgc/1788-update-getuserslist-in-responseops-to-not-have-multiple-return-types
=> Refactor get_users_list to only have one return type

.github/workflows/comment.yml, .github/workflows/main.yml, _infra/helm/response-operations-ui/Chart.yaml
This PR updates Github actions to fix "service_account_key" has been deprecated. Replacing it with google-github-actions/auth in both main.yml and comment.yml
Check that the actions have run correctly
main - https://github.com/ONSdigital/response-operations-ui/actions/runs/2621512043
comment - https://github.com/ONSdigital/response-operations-ui/runs/7200697706?check_suite_focus=true 
N.B I have a done a bit of magic with comment - issue_comment in an action will not run till it is merged meaning I couldn't test, however I changed it temporally to pull_request and removed the if in the yaml to prove it works. After which I reverted it back to issue_comment and re-instated the if
=> Fix security account key deprecation

_infra/helm/response-operations-ui/Chart.yaml, tests/views/test_message.py, tests/views/test_reporting_units.py
PR attached shaves about 40-50 seconds off the whole test suite.
The view tests are (time) expensive to run as each one seems to have a slow startup.  By combining some of the error tests and using the mocks between sets of them, we get the same coverage but the suite runs.
As well as this, we tidied up some of the tests and removed a few that were providing 0 value.
=> Improve test performance and layout

Dockerfile, _infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/admin/manage-user-accounts.html
The alphabetical selection menu was missing when a letter was selected and there were no users with this letter. This needed to be fixed so a user didn't have to keep clicking back to the previous selection. I have also added a section for the no user message so that there is even spacing when no users are found.
1. Log in as an admin user
2. Click the 'Manage user accounts' button
3. Click on a letter until the 'No results found' message is returned
4. The alphabetical menu should be present
https://trello.com/c/j7eVOjwg/1804-manage-user-accounts-does-not-display-alphabetical-selection-if-result-is-blank
=> Bug fix missing alphabetical selection

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/case_controller.py, response_operations_ui/templates/response-status.html, response_operations_ui/views/case.py, response_operations_ui/views/collection_exercise.py, tests/views/test_change_response_status.py
When going to view the response status of a case, if the case was in the NOTSTARTED state then there would be 2 visually identical 'Not started' radio buttons in addition to the 2 that set it into a completed state.  This PR fixes the issue and provides extra clarity in the form of a comment around the code to hopefully prevent it happening again.
For context, it happened because we recently added 2 new valid transitions from the NOTSTARTED state.  These states looped back to NOTSTARTED, but because they resulted in a NOTSTARTED end state, they were deemed 'allowed' and were put onto the screen.  This is because the responses page blindly takes the list of possible transitions and regardless of what state the case is currently in, if any possible transition ends up in the NOTSTARTED, …
=> Fix double 'not started' radio bug on response status page

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-view-sample-ci.html, response_operations_ui/views/collection_exercise.py, tests/views/test_collection_exercise.py
Before this PR, if the file extension was incorrect or there were too few columns, the only way to find out was to look at the url and see what random text was in the `error` param.  This PR removes the blobs of text from the url and instead uses `flash` to render the error on screen in the case of a failure in the sample upload process.
Also wrote stricter tests around this functionality as the previous tests were incredibly weak.
- Create a sample file and remove one of the columns
- Create collection exercise
- Go to upload the sample file, it'll now redirect you to the summary page with an error on screen and no junk text in the url.
- You can do the same test by uploading a file with the wrong extension, but you'll need to modify the html for the upload and change the `accepts` from …
=> Render error text to screen on sample upload failures

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/uaa_controller.py, response_operations_ui/templates/admin/manage-user-accounts.html, response_operations_ui/views/admin/manage_user_accounts.py
If you searched for an email with an apostrophe then it would cause an error.  Additionally, any error on the page would cause 2 text boxes to appear.  
- Deploy code and run tests to seed data
- Go to manage user accounts page and search for an an email with an apostrophe (example'blah@example.com) this should work now and not throw an error.
- Input an invalid email address.  You should only see one error message on the screen.
=> Fix error layout and apostrophes

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/__init__.py, response_operations_ui/controllers/collection_instrument_controllers.py, response_operations_ui/templates/ce-seft-instrument.html, response_operations_ui/views/collection_exercise.py, tests/views/test_collection_exercise.py
This PR updates SEFT collection instruments to call the delete end point in the collection instrument service rather than unlink
Deploy this [PR](https://github.com/ONSdigital/ras-collection-instrument/pull/282) to your environment and add and remove seft collection instruments. The other PR has more detailed instructions
=> Delete seft collection instrument

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/case_controller.py, response_operations_ui/templates/reporting-unit-survey.html, response_operations_ui/views/reporting_units.py, tests/controllers/test_case_controller.py, tests/views/test_reporting_units.py
Currently it's only possible to see the 12 most recent cases, if you want more (say, to change a status) then we have to go to the database for this.  This PR adds a 'hidden' url parameter, as in there is no UI element for it, `max-number-of-cases` that you can add to the `/reporting-units/<ru_ref>/surveys/<survey_id>` url to make it display more.
This is only really a temporary 'fix' until the work is done to make it possible to easily see all the cases for a survey.  It should, however, reduce the ops burden for us until it's implemented.
=> Add optional param for number of cases

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/errors/500-error.html
The text on the 500 error page was wrong as there is no 'contact us' page in response ops for the internal users to use.
=> Update text on 500 error page

.github/workflows/main.yml, _infra/helm/response-operations-ui/Chart.yaml
Currently on a push to a PR each repo builds to latest in onsrasrm-management, however this is the default artifact for all builds when using spinnaker. This means if any change to the charts are made and a PR is created it can and will break dev for everyone. 
Check the build (Publish dev Chart) and make sure it is writing naming the artifact correctly, it should be xx-pr-xx.tgz. You can also check on GCP in ons-rasrmbs-management that the artifact was written out at the right time
=> Update publish dev chart

.github/workflows/main.yml, Dockerfile, Makefile, Pipfile, Pipfile.lock, _infra/docker/Dockerfile, pyproject.toml
Upgrades python version to 3.11 and upgrades checkout and python-setup versions to something more current.
=> Upgrade python to 3.11 and update action versions

Makefile, Pipfile.lock, _infra/helm/response-operations-ui/Chart.yaml
pipenv check -i 51499 was introduced to temporarily remove the check on Wheel, now that it has been fixed, this PR updates the packages and removes the ignore
Make sure everything works
=> Remove pipenv check ignore

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/create-survey.html, response_operations_ui/templates/edit-survey-details.html, response_operations_ui/templates/surveys.html
This PR adds some text changes to the way surveyMode is displayed after design review.
Check new surveymode displays as `EQ and SEFT`
https://trello.com/c/2IZvLNGn/2450-multimode-mvp-creating-and-editing-existing-survey-to-add-multimode
=> Text changes to surveyMode

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/common/uaa.py, response_operations_ui/views/admin/manage_user_accounts.py, response_operations_ui/views/collection_exercise.py, response_operations_ui/views/messages.py, response_operations_ui/views/respondents.py, response_operations_ui/views/surveys.py, tests/views/test_collection_exercise.py
In https://github.com/ONSdigital/response-operations-ui/pull/826 there was a 'no access' page added for users accessing pages they didn't have permission for.  Because we had 2 different ways to check permissions, only half of the permission locked pages got this.  With this PR, all of the pages now function in the same way and all of them check permissions in the same way too for consistency.
=> Add missing NoPermissionError to remaining pages

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml, config.py, response_operations_ui/templates/create-survey.html, response_operations_ui/templates/edit-survey-details.html, response_operations_ui/views/surveys.py
This PR adds a feature flag for multimode
Run the applications with both MULTI_MODE_ENABLED=True and MULTI_MODE_ENABLED=False. Make sure it removes the EQ_AND_SEFT option from create survey and edit survey when false and has them when true
=> Add Mulitmode feature flag

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/survey.html
EQ_AND_SEFT currently doesn't show the Link collection instrument on the survey page, this adds it
Make sure the button appears for EQ_AND_SEFT and EQ, but not SEFT
=> Add Link collection instruments for EQ and SEFT on survey page

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/create-collection-exercise.html
The 'what is the period ID' part of the create-collection-exercise page was broken and just showing an arrow with no text.  This PR fixes it so it shows the title and help text
=> Fix broken details element

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/collection_instrument_controllers.py, response_operations_ui/views/collection_exercise.py, tests/controllers/test_collection_instrument_controller.py, tests/views/test_collection_exercise.py
This PR allows the message from CI upload to be displayed, it also adds a missing test
Test in conjunction with https://github.com/ONSdigital/ras-collection-instrument/pull/297
=> Extend collection instrument error message and add tests

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/surveys.html
This PR removes the table header (survey edit) from the surveys table.
Check the surveys table displays correctly without the survey edit table header. Check both with and without survey edit permissions. 
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=detail&selectedIssue=RAS-722
=> Remove survey edit table header

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ce-add-eq-ci.html, response_operations_ui/templates/collection_exercise/ce-collection-instrument-eq-section.html
Currently the csrf_token is not appearing on the eQ CI upload page, this is because {{ form }} is not being passed and therefore is not in scope. Naturally this will cause the app to logout 
You will need to change your config WTF_CSRF_ENABLED to be true if testing in dev. Once this has been done try to upload a collection instrument for an eQ
=> Add csrf token into eQ CI page

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/collection_instrument_controllers.py, response_operations_ui/views/collection_exercise.py, tests/views/test_collection_exercise.py
This PR updates the name of the end point it is calling
Test with https://github.com/ONSdigital/rm-collection-exercise-service/pull/312 and https://github.com/ONSdigital/ras-collection-instrument/pull/307 (description on collection instrument)
=> RAS-728 Ready for live button not appearing

Pipfile, Pipfile.lock, _infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/messages.html, response_operations_ui/templates/secure-message/misc-inbox.html, response_operations_ui/templates/secure-message/technical-inbox.html
djlint has been out of scope for security fixes but has been pinned for some time. This removes the pin and also fixes the linting errors.
Smoke test, especially messages.
`pipenv run djlint .` after a `pipenv install --dev`
RAS-866
=> Bump djlint and fix linting errors

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/views/collection_exercise.py, tests/test_data/collection_exercise/collection_exercise_details.json, tests/test_data/collection_exercise/collection_exercise_details_eq_both_ref_date.json, tests/test_data/collection_exercise/collection_exercise_details_sample_init_state.json, tests/test_data/collection_exercise/formatted_collection_exercise_details.json, tests/test_data/collection_exercise/formatted_collection_exercise_details_failedvalidation.json, tests/test_data/collection_exercise/formatted_collection_exercise_details_no_events.json, tests/test_data/collection_exercise/formatted_collection_exercise_details_no_sample.json, tests/test_data/collection_exercise/formatted_new_collection_exercise_details.json, tests/test_data/collection_exercise/seft_collection_exercise_details.json, tests/views/test_collection_exercise.py
Just updates to deal with updated return from collection exercise
Same as https://github.com/ONSdigital/response-operations-ui/pull/884
Deploy this PR to your environment
Ensure that https://github.com/ONSdigital/rm-collection-exercise-service/pull/318 is either merged or deploy it to your environment
Set up a collection exercise in Response Operations (only period ID is needed)
Place a pubsub message using and replacing your namespace, survey ID and period ID:
```
gcloud pubsub topics publish projects/ras-rm-dev/topics/supplementary-data-service-[your namespace] --message='{
"survey_id": [your survey ID],
"period_id": [your period ID],
"form_types": [
"0017",
"0123",
"0001"
],
"title": "A dataset version 4 for survey 2012 period 2013",
"sds_published_at": "2023-07-17T14:46:36Z", …
```
=> RAS-873 Show supplementary dataset ID in Rops collection exercise

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/controllers/collection_exercise_controllers.py, response_operations_ui/templates/collection_exercise/ce-header-section.html, response_operations_ui/views/collection_exercise.py
Add csv download option to response chase report. 
You will need this PR and the one for [reporting](https://github.com/ONSdigital/rm-reporting/pull/106) run locally or on GCP.  You will also need to seed some data or run the acceptance tests (if using acceptance, make sure you put enrol some extra respondents, as one user in one business is not overall reliable to test the functionality) Once you have done this make sure the report works as expected
=> RAS-272 Outputting the response chasing report as a csv as well as xlsx

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/contexts/collection_exercise.py, tests/context/conftest.py, tests/context/test_collection_exercise_context.py
In my last story I had to move response chasing, but I didn't change it, however what I hadn't picked up was there was data mutation on the dict here https://github.com/ONSdigital/response-operations-ui/blob/main/response_operations_ui/views/collection_exercise.py#L153. Basically doing this to the state element {"LIVE": "Live", "ENDED": "Ended"} Ironically we shouldn't be doing this but I am not going to unpick it now and just match it. 
Create a CE and put it in live/ended and make sure response chasing is there.
=> Correct response chasing error with status check

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml, config.py, response_operations_ui/contexts/case.py, response_operations_ui/views/case.py, tests/context/conftest.py, tests/context/test_case_context.py, tests/context/test_reporting_units_context.py, tests/test_data/case/case_events.json, tests/test_data/case/case_events_without_metadata.json, tests/test_data/case/case_events_without_partyId_in_metadata.json
Adds a 48 hour grace period to the survey status change (from complete to not started) 
- deploy this pr into your environment
- run the acceptance tests
- complete the survey in frontstage
- go to `/case/49900000001/response-status?survey=QBS&period=1912`
- make sure the radio to reset to Not Started is disabled
- go to the caseevent table in the case db and edit the date of the response (`OFFLINE_RESPONSE_PROCESSED`) to have happened at lease 48 hours ago
- refresh `/case/49900000001/response-status?survey=QBS&period=1912`
- make sure the radio is now enabled and you can reset the status
[RAS-1086](https://jira.ons.gov.uk/browse/RAS-1086)
=> RAS-1088 Implement 48 hour grace period for survey change of status

Pipfile, Pipfile.lock, _infra/helm/response-operations-ui/Chart.yaml
There is a vulnerability in Dnspython 2.5.0 which is used by email-validator, update email-validator to 2.1.1 which update Dnspython to 2.6.0
Make sure tests pass and everything works as before
=> RAS-1105 Update email-validator

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/contexts/reporting_units.py, response_operations_ui/controllers/party_controller.py, response_operations_ui/views/reporting_units.py, tests/context/conftest.py, tests/context/test_reporting_units_context.py, tests/controllers/test_party_controller.py, tests/test_data/party/enrolled_respondents.json, tests/views/test_reporting_units.py
Updates the call in view_reporting_unit_survey to use the new party service endpoint to find respondents by survey_id and business_id. There is also a small amount of refactoring and removal as well. view_reporting_unit_survey still needs a fair amount of work, so I have left it largely untouched bar the change in this PR
Deploy this PR and seed the db with data. Go to ROPs and search for a Reporting unit, drill down to the survey page of a business and confirm it still works and displays the correct information for respondents
Basically the PR is updating the Respondents section of the image above to call from a different endpoint. It is worth adding some more respondents, changing their state, sending a message and doing anything else you can think of
=> RAS-1111 Update ROPs to call new survey business end point

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/__init__.py, response_operations_ui/templates/layouts/base.html
There is a vulnerability with the package https://code.jquery.com/jquery-3.3.1.min.js. An investigation was conducted with the aim of removing this and any other jQuery references. This achieves that. 
Already approved in https://github.com/ONSdigital/response-operations-ui/pull/958
- Run unit tests
- Run acceptance tests
- As the base.html template has been affected, check all pages to see if they are correctly working
https://jira.ons.gov.uk/browse/RAS-1235
=> Investigate jQuery and resolve where possible - with verified bot signature

.github/workflows/main.yml, Pipfile, Pipfile.lock, _infra/docker/Dockerfile, _infra/helm/response-operations-ui/Chart.yaml, config.py, response_operations_ui/common/strtobool.py
Upgrades to Python 3.12. I believe this should also fix the jinja2 exploit.
General smoke test
RAS-1403
=> Upgrade to Python 3.12

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/radio-option-select-error-panel.html
The error summary for the my account page was mislabelled. This PR fixes the summary and solves the focus order problem it caused, highlighted in the DAC report. 
Deploy this PR and check a correct error summary is generated at the top of the page instead of an info summary. 
https://jira.ons.gov.uk/browse/RAS-1361
=> Fix my account error summary

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/partials/reporting-unit-tabs.html
DAC report - in order for screenreader software to properly detect that tabs are part of the same group, the tablist role needs to be added to the <ul> element
Do a respondent search and inspect the HTML
RAS-1363
=> Add tablist role to RU tabs

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/sign_in.html
This PR updates the error handling on the sign in page. It was identified in the DAC report that the error summary displayed a misleading please try again message. This has been updated with links to the specific errors. 
The error summary was also being displayed as an info summary which has been updated. 
Navigate to the sign in page and generate a sign in error. Check the resulting error summary and components meets the requirements on the DAC report. 
Check all other sign in page functionality remains unchanged. 
[RAS-1364](https://jira.ons.gov.uk/browse/RAS-1364)
=> Update sign in page error handling

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/surveys.html
This PR introduces a table header to the Edit Survey column to meet the DAC requirements and improve the navigation of the table for screen reader users. 
N.B. The design system does not currently allow individual columns to be sortable as it is applied in a macro to the entire table. Therefore a sort element is included with the header. 
https://github.com/ONSdigital/design-system/issues/2125
Deploy this PR and check there is now a table header on the Edit Survey column. 
[RAS-1366](https://jira.ons.gov.uk/browse/RAS-1366)
=> DAC Report - Surveys - Tables

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/view-sample-ci-summary.html, response_operations_ui/views/collection_exercise.py, tests/views/test_collection_exercise.py
Adds in the summary page for CIR 
create a collection exercise in rops, then navigated to http://localhost:8085/surveys/<survey_short_name>/<period_id>/view-sample-ci/summary,  it should be empty, but works. Now add a collection instrument into the exercise and return to the page, it should now show the table populated
=> RAS-1546 Create new 'Collection instruments step 2 of 2' page

_infra/helm/response-operations-ui/Chart.yaml, response_operations_ui/templates/collection_exercise/ci-versions.html, response_operations_ui/views/collection_exercise.py, tests/views/test_collection_exercise.py
This page introduces the CI versions page and displays the title. 
Assumption that the formtype will be passed through on clicking the choose version link on the previous page. 
There is a comment on the jira card that validation of url will be achieved on a separate card so this has been left off. 
Basic test introduced which can be extended with the rest of the functionality
Navigate to http://localhost:8085/surveys/<short_name>/<period_id>/view-sample-ci/summary/0001
[RAS-1547](https://jira.ons.gov.uk/browse/RAS-1547)
=> Introduce ci versions page

_infra/helm/response-operations-ui/Chart.yaml, _infra/helm/response-operations-ui/templates/deployment.yaml, _infra/helm/response-operations-ui/values.yaml
Adding support to allow Wiremock to be used in non formal env, or the CIR service to be used in prod/preprod
Ensure wiremock is used in dev/sandbox clusters, and that the actual CIR is used in preprod/prod
https://jira.ons.gov.uk/browse/RAS-1662
=> Add support for Wiremock in non formal envs
